<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Errors;

class GetMediaProvidersBadRequestThrowable extends \RuntimeException
{
    public GetMediaProvidersBadRequest $container;

    public function __construct(string $message, int $statusCode, GetMediaProvidersBadRequest $container)
    {
        parent::__construct($message, $statusCode);
        $this->container = $container;
    }
}