<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class Activity
{
	#[\JMS\Serializer\Annotation\SerializedName('uuid')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $uuid = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $type = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('cancellable')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $cancellable = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('userID')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $userID = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('title')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $title = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('subtitle')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $subtitle = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('progress')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $progress = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('Context')]
    #[\JMS\Serializer\Annotation\Type('LukeHagar\Plex_API\Models\Operations\Context')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?Context $context = null;
    
	public function __construct()
	{
		$this->uuid = null;
		$this->type = null;
		$this->cancellable = null;
		$this->userID = null;
		$this->title = null;
		$this->subtitle = null;
		$this->progress = null;
		$this->context = null;
	}
}
