<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


/** AddPlaylistContentsResponseBody - Playlist Updated */
class AddPlaylistContentsResponseBody
{
    /**
     *
     * @var ?AddPlaylistContentsMediaContainer $mediaContainer
     */
    #[\JMS\Serializer\Annotation\SerializedName('MediaContainer')]
    #[\JMS\Serializer\Annotation\Type('\LukeHagar\Plex_API\Models\Operations\AddPlaylistContentsMediaContainer|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?AddPlaylistContentsMediaContainer $mediaContainer = null;

    /**
     * @param  ?AddPlaylistContentsMediaContainer  $mediaContainer
     */
    public function __construct(?AddPlaylistContentsMediaContainer $mediaContainer = null)
    {
        $this->mediaContainer = $mediaContainer;
    }
}