<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


/** Indicate that you want to start download any updates found. */
enum Download: int
{
    case Zero = 0;
    case One = 1;
}
