<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class Feature
{
    /**
     *
     * @var ?string $key
     */
    #[\JMS\Serializer\Annotation\SerializedName('key')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $key = null;

    /**
     *
     * @var string $type
     */
    #[\JMS\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     *
     * @var ?string $flavor
     */
    #[\JMS\Serializer\Annotation\SerializedName('flavor')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $flavor = null;

    /**
     *
     * @var ?string $scrobbleKey
     */
    #[\JMS\Serializer\Annotation\SerializedName('scrobbleKey')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $scrobbleKey = null;

    /**
     *
     * @var ?string $unscrobbleKey
     */
    #[\JMS\Serializer\Annotation\SerializedName('unscrobbleKey')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $unscrobbleKey = null;

    /**
     * $directory
     *
     * @var ?array<GetMediaProvidersDirectory> $directory
     */
    #[\JMS\Serializer\Annotation\SerializedName('Directory')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetMediaProvidersDirectory>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $directory = null;

    /**
     * $action
     *
     * @var ?array<Action> $action
     */
    #[\JMS\Serializer\Annotation\SerializedName('Action')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\Action>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $action = null;

    /**
     * @param  string  $type
     * @param  ?string  $key
     * @param  ?string  $flavor
     * @param  ?string  $scrobbleKey
     * @param  ?string  $unscrobbleKey
     * @param  ?array<GetMediaProvidersDirectory>  $directory
     * @param  ?array<Action>  $action
     */
    public function __construct(string $type, ?string $key = null, ?string $flavor = null, ?string $scrobbleKey = null, ?string $unscrobbleKey = null, ?array $directory = null, ?array $action = null)
    {
        $this->type = $type;
        $this->key = $key;
        $this->flavor = $flavor;
        $this->scrobbleKey = $scrobbleKey;
        $this->unscrobbleKey = $unscrobbleKey;
        $this->directory = $directory;
        $this->action = $action;
    }
}