<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class GetAllLibrariesLocation
{
    /**
     *
     * @var int $id
     */
    #[\JMS\Serializer\Annotation\SerializedName('id')]
    public int $id;

    /**
     *
     * @var string $path
     */
    #[\JMS\Serializer\Annotation\SerializedName('path')]
    public string $path;

    /**
     * @param  int  $id
     * @param  string  $path
     */
    public function __construct(int $id, string $path)
    {
        $this->id = $id;
        $this->path = $path;
    }
}