<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;

use LukeHagar\Plex_API\Utils\SpeakeasyMetadata;
class GetBannerImageRequest
{
    /**
     * the id of the library item to return the children of.
     *
     * @var int $ratingKey
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=ratingKey')]
    public int $ratingKey;

    /**
     *
     * @var int $width
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=width')]
    public int $width;

    /**
     *
     * @var int $height
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=height')]
    public int $height;

    /**
     *
     * @var int $minSize
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=minSize')]
    public int $minSize;

    /**
     *
     * @var int $upscale
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=upscale')]
    public int $upscale;

    /**
     * Plex Authentication Token
     *
     * @var string $xPlexToken
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=X-Plex-Token')]
    public string $xPlexToken;

    /**
     * @param  int  $ratingKey
     * @param  int  $width
     * @param  int  $height
     * @param  int  $minSize
     * @param  int  $upscale
     * @param  string  $xPlexToken
     */
    public function __construct(int $ratingKey, int $width, int $height, int $minSize, int $upscale, string $xPlexToken)
    {
        $this->ratingKey = $ratingKey;
        $this->width = $width;
        $this->height = $height;
        $this->minSize = $minSize;
        $this->upscale = $upscale;
        $this->xPlexToken = $xPlexToken;
    }
}