<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class GetDevicesMediaContainer
{
    /**
     *
     * @var ?float $size
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('size')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $size = null;

    /**
     *
     * @var ?string $identifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('identifier')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $identifier = null;

    /**
     * $device
     *
     * @var ?array<Device> $device
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('Device')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\Device>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $device = null;

    /**
     * @param  ?float  $size
     * @param  ?string  $identifier
     * @param  ?array<Device>  $device
     * @phpstan-pure
     */
    public function __construct(?float $size = null, ?string $identifier = null, ?array $device = null)
    {
        $this->size = $size;
        $this->identifier = $identifier;
        $this->device = $device;
    }
}