<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


/** GetGlobalHubsResponseBody - returns global hubs */
class GetGlobalHubsResponseBody
{
    /**
     *
     * @var ?GetGlobalHubsMediaContainer $mediaContainer
     */
    #[\JMS\Serializer\Annotation\SerializedName('MediaContainer')]
    #[\JMS\Serializer\Annotation\Type('\LukeHagar\Plex_API\Models\Operations\GetGlobalHubsMediaContainer|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?GetGlobalHubsMediaContainer $mediaContainer = null;

    /**
     * @param  ?GetGlobalHubsMediaContainer  $mediaContainer
     */
    public function __construct(?GetGlobalHubsMediaContainer $mediaContainer = null)
    {
        $this->mediaContainer = $mediaContainer;
    }
}