<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


/**
 * GetLibraryItemsMediaContainer - The Meta object is only included in the response if the `includeMeta` parameter is set to `1`.
 *
 *
 */
class GetLibraryItemsMediaContainer
{
    /**
     * $type
     *
     * @var ?array<GetLibraryItemsType> $type
     */
    #[\JMS\Serializer\Annotation\SerializedName('Type')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetLibraryItemsType>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $type = null;

    /**
     * $fieldType
     *
     * @var ?array<GetLibraryItemsFieldType> $fieldType
     */
    #[\JMS\Serializer\Annotation\SerializedName('FieldType')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetLibraryItemsFieldType>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $fieldType = null;

    /**
     *
     * @var int $size
     */
    #[\JMS\Serializer\Annotation\SerializedName('size')]
    public int $size;

    /**
     *
     * @var int $totalSize
     */
    #[\JMS\Serializer\Annotation\SerializedName('totalSize')]
    public int $totalSize;

    /**
     *
     * @var int $offset
     */
    #[\JMS\Serializer\Annotation\SerializedName('offset')]
    public int $offset;

    /**
     *
     * @var string $content
     */
    #[\JMS\Serializer\Annotation\SerializedName('content')]
    public string $content;

    /**
     *
     * @var bool $allowSync
     */
    #[\JMS\Serializer\Annotation\SerializedName('allowSync')]
    public bool $allowSync;

    /**
     *
     * @var ?bool $nocache
     */
    #[\JMS\Serializer\Annotation\SerializedName('nocache')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?bool $nocache = null;

    /**
     *
     * @var string $art
     */
    #[\JMS\Serializer\Annotation\SerializedName('art')]
    public string $art;

    /**
     *
     * @var string $identifier
     */
    #[\JMS\Serializer\Annotation\SerializedName('identifier')]
    public string $identifier;

    /**
     *
     * @var int $librarySectionID
     */
    #[\JMS\Serializer\Annotation\SerializedName('librarySectionID')]
    public int $librarySectionID;

    /**
     *
     * @var string $librarySectionTitle
     */
    #[\JMS\Serializer\Annotation\SerializedName('librarySectionTitle')]
    public string $librarySectionTitle;

    /**
     *
     * @var string $librarySectionUUID
     */
    #[\JMS\Serializer\Annotation\SerializedName('librarySectionUUID')]
    public string $librarySectionUUID;

    /**
     *
     * @var string $mediaTagPrefix
     */
    #[\JMS\Serializer\Annotation\SerializedName('mediaTagPrefix')]
    public string $mediaTagPrefix;

    /**
     *
     * @var int $mediaTagVersion
     */
    #[\JMS\Serializer\Annotation\SerializedName('mediaTagVersion')]
    public int $mediaTagVersion;

    /**
     *
     * @var string $thumb
     */
    #[\JMS\Serializer\Annotation\SerializedName('thumb')]
    public string $thumb;

    /**
     *
     * @var string $title1
     */
    #[\JMS\Serializer\Annotation\SerializedName('title1')]
    public string $title1;

    /**
     *
     * @var string $title2
     */
    #[\JMS\Serializer\Annotation\SerializedName('title2')]
    public string $title2;

    /**
     *
     * @var string $viewGroup
     */
    #[\JMS\Serializer\Annotation\SerializedName('viewGroup')]
    public string $viewGroup;

    /**
     *
     * @var ?int $viewMode
     */
    #[\JMS\Serializer\Annotation\SerializedName('viewMode')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $viewMode = null;

    /**
     *
     * @var ?bool $mixedParents
     */
    #[\JMS\Serializer\Annotation\SerializedName('mixedParents')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?bool $mixedParents = null;

    /**
     * $metadata
     *
     * @var array<GetLibraryItemsMetadata> $metadata
     */
    #[\JMS\Serializer\Annotation\SerializedName('Metadata')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetLibraryItemsMetadata>')]
    public array $metadata;

    /**
     * The Meta object is only included in the response if the `includeMeta` parameter is set to `1`.
     *
     *
     *
     * @var ?GetLibraryItemsMeta $meta
     */
    #[\JMS\Serializer\Annotation\SerializedName('Meta')]
    #[\JMS\Serializer\Annotation\Type('\LukeHagar\Plex_API\Models\Operations\GetLibraryItemsMeta|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?GetLibraryItemsMeta $meta = null;

    /**
     * @param  int  $size
     * @param  int  $totalSize
     * @param  int  $offset
     * @param  string  $content
     * @param  bool  $allowSync
     * @param  string  $art
     * @param  string  $identifier
     * @param  int  $librarySectionID
     * @param  string  $librarySectionTitle
     * @param  string  $librarySectionUUID
     * @param  string  $mediaTagPrefix
     * @param  int  $mediaTagVersion
     * @param  string  $thumb
     * @param  string  $title1
     * @param  string  $title2
     * @param  string  $viewGroup
     * @param  array<GetLibraryItemsMetadata>  $metadata
     * @param  ?array<GetLibraryItemsType>  $type
     * @param  ?array<GetLibraryItemsFieldType>  $fieldType
     * @param  ?bool  $nocache
     * @param  ?int  $viewMode
     * @param  ?bool  $mixedParents
     * @param  ?GetLibraryItemsMeta  $meta
     */
    public function __construct(int $size, int $totalSize, int $offset, string $content, bool $allowSync, string $art, string $identifier, int $librarySectionID, string $librarySectionTitle, string $librarySectionUUID, string $mediaTagPrefix, int $mediaTagVersion, string $thumb, string $title1, string $title2, string $viewGroup, array $metadata, ?array $type = null, ?array $fieldType = null, ?bool $nocache = null, ?int $viewMode = null, ?bool $mixedParents = null, ?GetLibraryItemsMeta $meta = null)
    {
        $this->size = $size;
        $this->totalSize = $totalSize;
        $this->offset = $offset;
        $this->content = $content;
        $this->allowSync = $allowSync;
        $this->art = $art;
        $this->identifier = $identifier;
        $this->librarySectionID = $librarySectionID;
        $this->librarySectionTitle = $librarySectionTitle;
        $this->librarySectionUUID = $librarySectionUUID;
        $this->mediaTagPrefix = $mediaTagPrefix;
        $this->mediaTagVersion = $mediaTagVersion;
        $this->thumb = $thumb;
        $this->title1 = $title1;
        $this->title2 = $title2;
        $this->viewGroup = $viewGroup;
        $this->metadata = $metadata;
        $this->type = $type;
        $this->fieldType = $fieldType;
        $this->nocache = $nocache;
        $this->viewMode = $viewMode;
        $this->mixedParents = $mixedParents;
        $this->meta = $meta;
    }
}