<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;

use Brick\DateTime\LocalDate;
class GetLibraryHubsMetadata
{
    /**
     *
     * @var ?string $ratingKey
     */
    #[\JMS\Serializer\Annotation\SerializedName('ratingKey')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ratingKey = null;

    /**
     *
     * @var ?string $key
     */
    #[\JMS\Serializer\Annotation\SerializedName('key')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $key = null;

    /**
     *
     * @var ?string $guid
     */
    #[\JMS\Serializer\Annotation\SerializedName('guid')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $guid = null;

    /**
     *
     * @var ?string $studio
     */
    #[\JMS\Serializer\Annotation\SerializedName('studio')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $studio = null;

    /**
     *
     * @var ?string $type
     */
    #[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $type = null;

    /**
     *
     * @var ?string $title
     */
    #[\JMS\Serializer\Annotation\SerializedName('title')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $title = null;

    /**
     *
     * @var ?string $librarySectionTitle
     */
    #[\JMS\Serializer\Annotation\SerializedName('librarySectionTitle')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $librarySectionTitle = null;

    /**
     *
     * @var ?int $librarySectionID
     */
    #[\JMS\Serializer\Annotation\SerializedName('librarySectionID')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $librarySectionID = null;

    /**
     *
     * @var ?string $librarySectionKey
     */
    #[\JMS\Serializer\Annotation\SerializedName('librarySectionKey')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $librarySectionKey = null;

    /**
     *
     * @var ?string $contentRating
     */
    #[\JMS\Serializer\Annotation\SerializedName('contentRating')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $contentRating = null;

    /**
     *
     * @var ?string $summary
     */
    #[\JMS\Serializer\Annotation\SerializedName('summary')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $summary = null;

    /**
     *
     * @var ?float $rating
     */
    #[\JMS\Serializer\Annotation\SerializedName('rating')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $rating = null;

    /**
     *
     * @var ?float $audienceRating
     */
    #[\JMS\Serializer\Annotation\SerializedName('audienceRating')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $audienceRating = null;

    /**
     *
     * @var ?int $viewCount
     */
    #[\JMS\Serializer\Annotation\SerializedName('viewCount')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $viewCount = null;

    /**
     *
     * @var ?int $lastViewedAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('lastViewedAt')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $lastViewedAt = null;

    /**
     *
     * @var ?int $year
     */
    #[\JMS\Serializer\Annotation\SerializedName('year')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $year = null;

    /**
     *
     * @var ?string $tagline
     */
    #[\JMS\Serializer\Annotation\SerializedName('tagline')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $tagline = null;

    /**
     *
     * @var ?string $thumb
     */
    #[\JMS\Serializer\Annotation\SerializedName('thumb')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $thumb = null;

    /**
     *
     * @var ?string $art
     */
    #[\JMS\Serializer\Annotation\SerializedName('art')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $art = null;

    /**
     *
     * @var ?int $duration
     */
    #[\JMS\Serializer\Annotation\SerializedName('duration')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $duration = null;

    /**
     *
     * @var ?LocalDate $originallyAvailableAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('originallyAvailableAt')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?LocalDate $originallyAvailableAt = null;

    /**
     *
     * @var ?int $addedAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('addedAt')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $addedAt = null;

    /**
     *
     * @var ?int $updatedAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('updatedAt')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $updatedAt = null;

    /**
     *
     * @var ?string $audienceRatingImage
     */
    #[\JMS\Serializer\Annotation\SerializedName('audienceRatingImage')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $audienceRatingImage = null;

    /**
     *
     * @var ?string $primaryExtraKey
     */
    #[\JMS\Serializer\Annotation\SerializedName('primaryExtraKey')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $primaryExtraKey = null;

    /**
     *
     * @var ?string $ratingImage
     */
    #[\JMS\Serializer\Annotation\SerializedName('ratingImage')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ratingImage = null;

    /**
     * $media
     *
     * @var ?array<GetLibraryHubsMedia> $media
     */
    #[\JMS\Serializer\Annotation\SerializedName('Media')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetLibraryHubsMedia>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $media = null;

    /**
     * $genre
     *
     * @var ?array<GetLibraryHubsGenre> $genre
     */
    #[\JMS\Serializer\Annotation\SerializedName('Genre')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetLibraryHubsGenre>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $genre = null;

    /**
     * $country
     *
     * @var ?array<GetLibraryHubsCountry> $country
     */
    #[\JMS\Serializer\Annotation\SerializedName('Country')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetLibraryHubsCountry>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $country = null;

    /**
     * $director
     *
     * @var ?array<GetLibraryHubsDirector> $director
     */
    #[\JMS\Serializer\Annotation\SerializedName('Director')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetLibraryHubsDirector>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $director = null;

    /**
     * $role
     *
     * @var ?array<GetLibraryHubsRole> $role
     */
    #[\JMS\Serializer\Annotation\SerializedName('Role')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetLibraryHubsRole>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $role = null;

    /**
     * $writer
     *
     * @var ?array<GetLibraryHubsWriter> $writer
     */
    #[\JMS\Serializer\Annotation\SerializedName('Writer')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetLibraryHubsWriter>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $writer = null;

    /**
     *
     * @var ?int $skipCount
     */
    #[\JMS\Serializer\Annotation\SerializedName('skipCount')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $skipCount = null;

    /**
     *
     * @var ?string $chapterSource
     */
    #[\JMS\Serializer\Annotation\SerializedName('chapterSource')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $chapterSource = null;

    /**
     * @param  ?string  $ratingKey
     * @param  ?string  $key
     * @param  ?string  $guid
     * @param  ?string  $studio
     * @param  ?string  $type
     * @param  ?string  $title
     * @param  ?string  $librarySectionTitle
     * @param  ?int  $librarySectionID
     * @param  ?string  $librarySectionKey
     * @param  ?string  $contentRating
     * @param  ?string  $summary
     * @param  ?float  $rating
     * @param  ?float  $audienceRating
     * @param  ?int  $viewCount
     * @param  ?int  $lastViewedAt
     * @param  ?int  $year
     * @param  ?string  $tagline
     * @param  ?string  $thumb
     * @param  ?string  $art
     * @param  ?int  $duration
     * @param  ?LocalDate  $originallyAvailableAt
     * @param  ?int  $addedAt
     * @param  ?int  $updatedAt
     * @param  ?string  $audienceRatingImage
     * @param  ?string  $primaryExtraKey
     * @param  ?string  $ratingImage
     * @param  ?array<GetLibraryHubsMedia>  $media
     * @param  ?array<GetLibraryHubsGenre>  $genre
     * @param  ?array<GetLibraryHubsCountry>  $country
     * @param  ?array<GetLibraryHubsDirector>  $director
     * @param  ?array<GetLibraryHubsRole>  $role
     * @param  ?array<GetLibraryHubsWriter>  $writer
     * @param  ?int  $skipCount
     * @param  ?string  $chapterSource
     */
    public function __construct(?string $ratingKey = null, ?string $key = null, ?string $guid = null, ?string $studio = null, ?string $type = null, ?string $title = null, ?string $librarySectionTitle = null, ?int $librarySectionID = null, ?string $librarySectionKey = null, ?string $contentRating = null, ?string $summary = null, ?float $rating = null, ?float $audienceRating = null, ?int $viewCount = null, ?int $lastViewedAt = null, ?int $year = null, ?string $tagline = null, ?string $thumb = null, ?string $art = null, ?int $duration = null, ?LocalDate $originallyAvailableAt = null, ?int $addedAt = null, ?int $updatedAt = null, ?string $audienceRatingImage = null, ?string $primaryExtraKey = null, ?string $ratingImage = null, ?array $media = null, ?array $genre = null, ?array $country = null, ?array $director = null, ?array $role = null, ?array $writer = null, ?int $skipCount = null, ?string $chapterSource = null)
    {
        $this->ratingKey = $ratingKey;
        $this->key = $key;
        $this->guid = $guid;
        $this->studio = $studio;
        $this->type = $type;
        $this->title = $title;
        $this->librarySectionTitle = $librarySectionTitle;
        $this->librarySectionID = $librarySectionID;
        $this->librarySectionKey = $librarySectionKey;
        $this->contentRating = $contentRating;
        $this->summary = $summary;
        $this->rating = $rating;
        $this->audienceRating = $audienceRating;
        $this->viewCount = $viewCount;
        $this->lastViewedAt = $lastViewedAt;
        $this->year = $year;
        $this->tagline = $tagline;
        $this->thumb = $thumb;
        $this->art = $art;
        $this->duration = $duration;
        $this->originallyAvailableAt = $originallyAvailableAt;
        $this->addedAt = $addedAt;
        $this->updatedAt = $updatedAt;
        $this->audienceRatingImage = $audienceRatingImage;
        $this->primaryExtraKey = $primaryExtraKey;
        $this->ratingImage = $ratingImage;
        $this->media = $media;
        $this->genre = $genre;
        $this->country = $country;
        $this->director = $director;
        $this->role = $role;
        $this->writer = $writer;
        $this->skipCount = $skipCount;
        $this->chapterSource = $chapterSource;
    }
}