<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;

use \LukeHagar\Plex_API\Utils\SpeakeasyMetadata;
class GetLibraryRequest
{
    /**
     * the Id of the library to query
     * 
     * @var float $sectionId
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=sectionId')]
    public float $sectionId;
    
    /**
     * Whether or not to include details for a section (types, filters, and sorts). 
     * 
     * Only exists for backwards compatibility, media providers other than the server libraries have it on always.
     * 
     * 
     * @var ?\LukeHagar\Plex_API\Models\Operations\IncludeDetails $includeDetails
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=includeDetails')]
    public ?IncludeDetails $includeDetails = null;
    
	public function __construct()
	{
		$this->sectionId = 0;
		$this->includeDetails = null;
	}
}
