<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class GetLibraryDetailsField
{
    /**
     *
     * @var ?string $key
     */
    #[\JMS\Serializer\Annotation\SerializedName('key')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $key = null;

    /**
     *
     * @var ?string $title
     */
    #[\JMS\Serializer\Annotation\SerializedName('title')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $title = null;

    /**
     *
     * @var ?string $type
     */
    #[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $type = null;

    /**
     *
     * @var ?string $subType
     */
    #[\JMS\Serializer\Annotation\SerializedName('subType')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $subType = null;

    /**
     * @param  ?string  $key
     * @param  ?string  $title
     * @param  ?string  $type
     * @param  ?string  $subType
     */
    public function __construct(?string $key = null, ?string $title = null, ?string $type = null, ?string $subType = null)
    {
        $this->key = $key;
        $this->title = $title;
        $this->type = $type;
        $this->subType = $subType;
    }
}