<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class GetLibraryItemsSort
{
    /**
     *
     * @var ?string $default
     */
    #[\JMS\Serializer\Annotation\SerializedName('default')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $default = null;

    /**
     *
     * @var string $defaultDirection
     */
    #[\JMS\Serializer\Annotation\SerializedName('defaultDirection')]
    public string $defaultDirection;

    /**
     *
     * @var ?string $descKey
     */
    #[\JMS\Serializer\Annotation\SerializedName('descKey')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $descKey = null;

    /**
     *
     * @var ?string $firstCharacterKey
     */
    #[\JMS\Serializer\Annotation\SerializedName('firstCharacterKey')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $firstCharacterKey = null;

    /**
     *
     * @var string $key
     */
    #[\JMS\Serializer\Annotation\SerializedName('key')]
    public string $key;

    /**
     *
     * @var string $title
     */
    #[\JMS\Serializer\Annotation\SerializedName('title')]
    public string $title;

    /**
     * @param  string  $defaultDirection
     * @param  string  $key
     * @param  string  $title
     * @param  ?string  $default
     * @param  ?string  $descKey
     * @param  ?string  $firstCharacterKey
     */
    public function __construct(string $defaultDirection, string $key, string $title, ?string $default = null, ?string $descKey = null, ?string $firstCharacterKey = null)
    {
        $this->defaultDirection = $defaultDirection;
        $this->key = $key;
        $this->title = $title;
        $this->default = $default;
        $this->descKey = $descKey;
        $this->firstCharacterKey = $firstCharacterKey;
    }
}