<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class GetLibraryDetailsType
{
    /**
     *
     * @var ?string $key
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('key')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $key = null;

    /**
     *
     * @var ?string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $type = null;

    /**
     *
     * @var ?string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $title = null;

    /**
     *
     * @var ?bool $active
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('active')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $active = null;

    /**
     * $filter
     *
     * @var ?array<GetLibraryDetailsFilter> $filter
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('Filter')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetLibraryDetailsFilter>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $filter = null;

    /**
     * $sort
     *
     * @var ?array<GetLibraryDetailsSort> $sort
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('Sort')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetLibraryDetailsSort>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $sort = null;

    /**
     * $field
     *
     * @var ?array<GetLibraryDetailsField> $field
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('Field')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetLibraryDetailsField>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $field = null;

    /**
     * @param  ?string  $key
     * @param  ?string  $type
     * @param  ?string  $title
     * @param  ?bool  $active
     * @param  ?array<GetLibraryDetailsFilter>  $filter
     * @param  ?array<GetLibraryDetailsSort>  $sort
     * @param  ?array<GetLibraryDetailsField>  $field
     */
    public function __construct(?string $key = null, ?string $type = null, ?string $title = null, ?bool $active = null, ?array $filter = null, ?array $sort = null, ?array $field = null)
    {
        $this->key = $key;
        $this->type = $type;
        $this->title = $title;
        $this->active = $active;
        $this->filter = $filter;
        $this->sort = $sort;
        $this->field = $field;
    }
}