<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class GetMetadataChildrenMetadata
{
    /**
     *
     * @var ?string $ratingKey
     */
    #[\JMS\Serializer\Annotation\SerializedName('ratingKey')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $ratingKey = null;

    /**
     *
     * @var ?string $key
     */
    #[\JMS\Serializer\Annotation\SerializedName('key')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $key = null;

    /**
     *
     * @var ?string $parentRatingKey
     */
    #[\JMS\Serializer\Annotation\SerializedName('parentRatingKey')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $parentRatingKey = null;

    /**
     *
     * @var ?string $guid
     */
    #[\JMS\Serializer\Annotation\SerializedName('guid')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $guid = null;

    /**
     *
     * @var ?string $parentGuid
     */
    #[\JMS\Serializer\Annotation\SerializedName('parentGuid')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $parentGuid = null;

    /**
     *
     * @var ?string $parentStudio
     */
    #[\JMS\Serializer\Annotation\SerializedName('parentStudio')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $parentStudio = null;

    /**
     *
     * @var ?string $type
     */
    #[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $type = null;

    /**
     *
     * @var ?string $title
     */
    #[\JMS\Serializer\Annotation\SerializedName('title')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $title = null;

    /**
     *
     * @var ?string $parentKey
     */
    #[\JMS\Serializer\Annotation\SerializedName('parentKey')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $parentKey = null;

    /**
     *
     * @var ?string $parentTitle
     */
    #[\JMS\Serializer\Annotation\SerializedName('parentTitle')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $parentTitle = null;

    /**
     *
     * @var ?string $summary
     */
    #[\JMS\Serializer\Annotation\SerializedName('summary')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $summary = null;

    /**
     *
     * @var ?int $index
     */
    #[\JMS\Serializer\Annotation\SerializedName('index')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $index = null;

    /**
     *
     * @var ?int $parentIndex
     */
    #[\JMS\Serializer\Annotation\SerializedName('parentIndex')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $parentIndex = null;

    /**
     *
     * @var ?int $viewCount
     */
    #[\JMS\Serializer\Annotation\SerializedName('viewCount')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $viewCount = null;

    /**
     *
     * @var ?int $lastViewedAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('lastViewedAt')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $lastViewedAt = null;

    /**
     *
     * @var ?int $parentYear
     */
    #[\JMS\Serializer\Annotation\SerializedName('parentYear')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $parentYear = null;

    /**
     *
     * @var ?string $thumb
     */
    #[\JMS\Serializer\Annotation\SerializedName('thumb')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $thumb = null;

    /**
     *
     * @var ?string $art
     */
    #[\JMS\Serializer\Annotation\SerializedName('art')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $art = null;

    /**
     *
     * @var ?string $parentThumb
     */
    #[\JMS\Serializer\Annotation\SerializedName('parentThumb')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $parentThumb = null;

    /**
     *
     * @var ?string $parentTheme
     */
    #[\JMS\Serializer\Annotation\SerializedName('parentTheme')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $parentTheme = null;

    /**
     *
     * @var ?int $leafCount
     */
    #[\JMS\Serializer\Annotation\SerializedName('leafCount')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $leafCount = null;

    /**
     *
     * @var ?int $viewedLeafCount
     */
    #[\JMS\Serializer\Annotation\SerializedName('viewedLeafCount')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $viewedLeafCount = null;

    /**
     *
     * @var ?int $addedAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('addedAt')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $addedAt = null;

    /**
     *
     * @var ?int $updatedAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('updatedAt')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $updatedAt = null;

    /**
     *
     * @var ?int $userRating
     */
    #[\JMS\Serializer\Annotation\SerializedName('userRating')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $userRating = null;

    /**
     *
     * @var ?int $skipCount
     */
    #[\JMS\Serializer\Annotation\SerializedName('skipCount')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $skipCount = null;

    /**
     *
     * @var ?int $lastRatedAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('lastRatedAt')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $lastRatedAt = null;

    /**
     * @param  ?string  $ratingKey
     * @param  ?string  $key
     * @param  ?string  $parentRatingKey
     * @param  ?string  $guid
     * @param  ?string  $parentGuid
     * @param  ?string  $parentStudio
     * @param  ?string  $type
     * @param  ?string  $title
     * @param  ?string  $parentKey
     * @param  ?string  $parentTitle
     * @param  ?string  $summary
     * @param  ?int  $index
     * @param  ?int  $parentIndex
     * @param  ?int  $viewCount
     * @param  ?int  $lastViewedAt
     * @param  ?int  $parentYear
     * @param  ?string  $thumb
     * @param  ?string  $art
     * @param  ?string  $parentThumb
     * @param  ?string  $parentTheme
     * @param  ?int  $leafCount
     * @param  ?int  $viewedLeafCount
     * @param  ?int  $addedAt
     * @param  ?int  $updatedAt
     * @param  ?int  $userRating
     * @param  ?int  $skipCount
     * @param  ?int  $lastRatedAt
     */
    public function __construct(?string $ratingKey = null, ?string $key = null, ?string $parentRatingKey = null, ?string $guid = null, ?string $parentGuid = null, ?string $parentStudio = null, ?string $type = null, ?string $title = null, ?string $parentKey = null, ?string $parentTitle = null, ?string $summary = null, ?int $index = null, ?int $parentIndex = null, ?int $viewCount = null, ?int $lastViewedAt = null, ?int $parentYear = null, ?string $thumb = null, ?string $art = null, ?string $parentThumb = null, ?string $parentTheme = null, ?int $leafCount = null, ?int $viewedLeafCount = null, ?int $addedAt = null, ?int $updatedAt = null, ?int $userRating = null, ?int $skipCount = null, ?int $lastRatedAt = null)
    {
        $this->ratingKey = $ratingKey;
        $this->key = $key;
        $this->parentRatingKey = $parentRatingKey;
        $this->guid = $guid;
        $this->parentGuid = $parentGuid;
        $this->parentStudio = $parentStudio;
        $this->type = $type;
        $this->title = $title;
        $this->parentKey = $parentKey;
        $this->parentTitle = $parentTitle;
        $this->summary = $summary;
        $this->index = $index;
        $this->parentIndex = $parentIndex;
        $this->viewCount = $viewCount;
        $this->lastViewedAt = $lastViewedAt;
        $this->parentYear = $parentYear;
        $this->thumb = $thumb;
        $this->art = $art;
        $this->parentThumb = $parentThumb;
        $this->parentTheme = $parentTheme;
        $this->leafCount = $leafCount;
        $this->viewedLeafCount = $viewedLeafCount;
        $this->addedAt = $addedAt;
        $this->updatedAt = $updatedAt;
        $this->userRating = $userRating;
        $this->skipCount = $skipCount;
        $this->lastRatedAt = $lastRatedAt;
    }
}