<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;

use LukeHagar\Plex_API\Utils\SpeakeasyMetadata;
class GetMediaMetaDataRequest
{
    /**
     * The id(s) of the library item(s) to return metadata for. Can be a single ID or comma-separated list of IDs.
     *
     * @var string $ratingKey
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=ratingKey')]
    public string $ratingKey;

    /**
     * Include concerts data if set to true.
     *
     * @var ?bool $includeConcerts
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=includeConcerts')]
    public ?bool $includeConcerts = null;

    /**
     * Include extra content (e.g. bonus features).
     *
     * @var ?bool $includeExtras
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=includeExtras')]
    public ?bool $includeExtras = null;

    /**
     * Include on-deck items.
     *
     * @var ?bool $includeOnDeck
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=includeOnDeck')]
    public ?bool $includeOnDeck = null;

    /**
     * Include popular leaves (episodes/chapters).
     *
     * @var ?bool $includePopularLeaves
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=includePopularLeaves')]
    public ?bool $includePopularLeaves = null;

    /**
     * Include preferences information.
     *
     * @var ?bool $includePreferences
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=includePreferences')]
    public ?bool $includePreferences = null;

    /**
     * Include reviews for the content.
     *
     * @var ?bool $includeReviews
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=includeReviews')]
    public ?bool $includeReviews = null;

    /**
     * Include chapter details.
     *
     * @var ?bool $includeChapters
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=includeChapters')]
    public ?bool $includeChapters = null;

    /**
     * Include station data.
     *
     * @var ?bool $includeStations
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=includeStations')]
    public ?bool $includeStations = null;

    /**
     * Include external media data.
     *
     * @var ?bool $includeExternalMedia
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=includeExternalMedia')]
    public ?bool $includeExternalMedia = null;

    /**
     * Trigger asynchronous metadata augmentation.
     *
     * @var ?bool $asyncAugmentMetadata
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=asyncAugmentMetadata')]
    public ?bool $asyncAugmentMetadata = null;

    /**
     * Trigger asynchronous file checking.
     *
     * @var ?bool $asyncCheckFiles
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=asyncCheckFiles')]
    public ?bool $asyncCheckFiles = null;

    /**
     * Trigger asynchronous refresh of analysis.
     *
     * @var ?bool $asyncRefreshAnalysis
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=asyncRefreshAnalysis')]
    public ?bool $asyncRefreshAnalysis = null;

    /**
     * Trigger asynchronous refresh of the local media agent.
     *
     * @var ?bool $asyncRefreshLocalMediaAgent
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=asyncRefreshLocalMediaAgent')]
    public ?bool $asyncRefreshLocalMediaAgent = null;

    /**
     * @param  string  $ratingKey
     * @param  ?bool  $includeConcerts
     * @param  ?bool  $includeExtras
     * @param  ?bool  $includeOnDeck
     * @param  ?bool  $includePopularLeaves
     * @param  ?bool  $includePreferences
     * @param  ?bool  $includeReviews
     * @param  ?bool  $includeChapters
     * @param  ?bool  $includeStations
     * @param  ?bool  $includeExternalMedia
     * @param  ?bool  $asyncAugmentMetadata
     * @param  ?bool  $asyncCheckFiles
     * @param  ?bool  $asyncRefreshAnalysis
     * @param  ?bool  $asyncRefreshLocalMediaAgent
     * @phpstan-pure
     */
    public function __construct(string $ratingKey, ?bool $includeConcerts = null, ?bool $includeExtras = null, ?bool $includeOnDeck = null, ?bool $includePopularLeaves = null, ?bool $includePreferences = null, ?bool $includeReviews = null, ?bool $includeChapters = null, ?bool $includeStations = null, ?bool $includeExternalMedia = null, ?bool $asyncAugmentMetadata = null, ?bool $asyncCheckFiles = null, ?bool $asyncRefreshAnalysis = null, ?bool $asyncRefreshLocalMediaAgent = null)
    {
        $this->ratingKey = $ratingKey;
        $this->includeConcerts = $includeConcerts;
        $this->includeExtras = $includeExtras;
        $this->includeOnDeck = $includeOnDeck;
        $this->includePopularLeaves = $includePopularLeaves;
        $this->includePreferences = $includePreferences;
        $this->includeReviews = $includeReviews;
        $this->includeChapters = $includeChapters;
        $this->includeStations = $includeStations;
        $this->includeExternalMedia = $includeExternalMedia;
        $this->asyncAugmentMetadata = $asyncAugmentMetadata;
        $this->asyncCheckFiles = $asyncCheckFiles;
        $this->asyncRefreshAnalysis = $asyncRefreshAnalysis;
        $this->asyncRefreshLocalMediaAgent = $asyncRefreshLocalMediaAgent;
    }
}