<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class GetMediaMetaDataRatings
{
    /**
     * The image or reference for the rating.
     *
     * @var string $image
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('image')]
    public string $image;

    /**
     * The rating value.
     *
     * @var float $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    public float $value;

    /**
     * The type of rating (e.g., audience, critic).
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     * @param  string  $image
     * @param  float  $value
     * @param  string  $type
     * @phpstan-pure
     */
    public function __construct(string $image, float $value, string $type)
    {
        $this->image = $image;
        $this->value = $value;
        $this->type = $type;
    }
}