<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class GetMetadataChildrenMediaContainer
{
    /**
     *
     * @var ?int $size
     */
    #[\JMS\Serializer\Annotation\SerializedName('size')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $size = null;

    /**
     *
     * @var ?bool $allowSync
     */
    #[\JMS\Serializer\Annotation\SerializedName('allowSync')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $allowSync = null;

    /**
     *
     * @var ?string $art
     */
    #[\JMS\Serializer\Annotation\SerializedName('art')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $art = null;

    /**
     *
     * @var ?string $identifier
     */
    #[\JMS\Serializer\Annotation\SerializedName('identifier')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $identifier = null;

    /**
     *
     * @var ?string $key
     */
    #[\JMS\Serializer\Annotation\SerializedName('key')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $key = null;

    /**
     *
     * @var ?int $librarySectionID
     */
    #[\JMS\Serializer\Annotation\SerializedName('librarySectionID')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $librarySectionID = null;

    /**
     *
     * @var ?string $librarySectionTitle
     */
    #[\JMS\Serializer\Annotation\SerializedName('librarySectionTitle')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $librarySectionTitle = null;

    /**
     *
     * @var ?string $librarySectionUUID
     */
    #[\JMS\Serializer\Annotation\SerializedName('librarySectionUUID')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $librarySectionUUID = null;

    /**
     *
     * @var ?string $mediaTagPrefix
     */
    #[\JMS\Serializer\Annotation\SerializedName('mediaTagPrefix')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $mediaTagPrefix = null;

    /**
     *
     * @var ?int $mediaTagVersion
     */
    #[\JMS\Serializer\Annotation\SerializedName('mediaTagVersion')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $mediaTagVersion = null;

    /**
     *
     * @var ?bool $nocache
     */
    #[\JMS\Serializer\Annotation\SerializedName('nocache')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $nocache = null;

    /**
     *
     * @var ?int $parentIndex
     */
    #[\JMS\Serializer\Annotation\SerializedName('parentIndex')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $parentIndex = null;

    /**
     *
     * @var ?string $parentTitle
     */
    #[\JMS\Serializer\Annotation\SerializedName('parentTitle')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $parentTitle = null;

    /**
     *
     * @var ?int $parentYear
     */
    #[\JMS\Serializer\Annotation\SerializedName('parentYear')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $parentYear = null;

    /**
     *
     * @var ?string $summary
     */
    #[\JMS\Serializer\Annotation\SerializedName('summary')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $summary = null;

    /**
     *
     * @var ?string $theme
     */
    #[\JMS\Serializer\Annotation\SerializedName('theme')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $theme = null;

    /**
     *
     * @var ?string $thumb
     */
    #[\JMS\Serializer\Annotation\SerializedName('thumb')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $thumb = null;

    /**
     *
     * @var ?string $title1
     */
    #[\JMS\Serializer\Annotation\SerializedName('title1')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $title1 = null;

    /**
     *
     * @var ?string $title2
     */
    #[\JMS\Serializer\Annotation\SerializedName('title2')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $title2 = null;

    /**
     *
     * @var ?string $viewGroup
     */
    #[\JMS\Serializer\Annotation\SerializedName('viewGroup')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $viewGroup = null;

    /**
     *
     * @var ?int $viewMode
     */
    #[\JMS\Serializer\Annotation\SerializedName('viewMode')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $viewMode = null;

    /**
     * $directory
     *
     * @var ?array<GetMetadataChildrenDirectory> $directory
     */
    #[\JMS\Serializer\Annotation\SerializedName('Directory')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetMetadataChildrenDirectory>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $directory = null;

    /**
     * $metadata
     *
     * @var ?array<GetMetadataChildrenMetadata> $metadata
     */
    #[\JMS\Serializer\Annotation\SerializedName('Metadata')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetMetadataChildrenMetadata>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $metadata = null;

    /**
     * @param  ?int  $size
     * @param  ?bool  $allowSync
     * @param  ?string  $art
     * @param  ?string  $identifier
     * @param  ?string  $key
     * @param  ?int  $librarySectionID
     * @param  ?string  $librarySectionTitle
     * @param  ?string  $librarySectionUUID
     * @param  ?string  $mediaTagPrefix
     * @param  ?int  $mediaTagVersion
     * @param  ?bool  $nocache
     * @param  ?int  $parentIndex
     * @param  ?string  $parentTitle
     * @param  ?int  $parentYear
     * @param  ?string  $summary
     * @param  ?string  $theme
     * @param  ?string  $thumb
     * @param  ?string  $title1
     * @param  ?string  $title2
     * @param  ?string  $viewGroup
     * @param  ?int  $viewMode
     * @param  ?array<GetMetadataChildrenDirectory>  $directory
     * @param  ?array<GetMetadataChildrenMetadata>  $metadata
     */
    public function __construct(?int $size = null, ?bool $allowSync = null, ?string $art = null, ?string $identifier = null, ?string $key = null, ?int $librarySectionID = null, ?string $librarySectionTitle = null, ?string $librarySectionUUID = null, ?string $mediaTagPrefix = null, ?int $mediaTagVersion = null, ?bool $nocache = null, ?int $parentIndex = null, ?string $parentTitle = null, ?int $parentYear = null, ?string $summary = null, ?string $theme = null, ?string $thumb = null, ?string $title1 = null, ?string $title2 = null, ?string $viewGroup = null, ?int $viewMode = null, ?array $directory = null, ?array $metadata = null)
    {
        $this->size = $size;
        $this->allowSync = $allowSync;
        $this->art = $art;
        $this->identifier = $identifier;
        $this->key = $key;
        $this->librarySectionID = $librarySectionID;
        $this->librarySectionTitle = $librarySectionTitle;
        $this->librarySectionUUID = $librarySectionUUID;
        $this->mediaTagPrefix = $mediaTagPrefix;
        $this->mediaTagVersion = $mediaTagVersion;
        $this->nocache = $nocache;
        $this->parentIndex = $parentIndex;
        $this->parentTitle = $parentTitle;
        $this->parentYear = $parentYear;
        $this->summary = $summary;
        $this->theme = $theme;
        $this->thumb = $thumb;
        $this->title1 = $title1;
        $this->title2 = $title2;
        $this->viewGroup = $viewGroup;
        $this->viewMode = $viewMode;
        $this->directory = $directory;
        $this->metadata = $metadata;
    }
}