<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


/** GetMediaMetaDataAttributes - Attributes associated with the marker. */
class GetMediaMetaDataAttributes
{
    /**
     * The identifier for the attributes.
     *
     * @var int $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public int $id;

    /**
     * The version number of the marker attributes.
     *
     * @var ?int $version
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('version')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $version = null;

    /**
     * @param  int  $id
     * @param  ?int  $version
     * @phpstan-pure
     */
    public function __construct(int $id, ?int $version = null)
    {
        $this->id = $id;
        $this->version = $version;
    }
}