<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


/** GetMediaProvidersResponseBody - Media providers and their features */
class GetMediaProvidersResponseBody
{
    /**
     *
     * @var ?GetMediaProvidersMediaContainer $mediaContainer
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('MediaContainer')]
    #[\Speakeasy\Serializer\Annotation\Type('\LukeHagar\Plex_API\Models\Operations\GetMediaProvidersMediaContainer|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?GetMediaProvidersMediaContainer $mediaContainer = null;

    /**
     * @param  ?GetMediaProvidersMediaContainer  $mediaContainer
     * @phpstan-pure
     */
    public function __construct(?GetMediaProvidersMediaContainer $mediaContainer = null)
    {
        $this->mediaContainer = $mediaContainer;
    }
}