<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class GetMediaProvidersMediaContainer
{
    /**
     *
     * @var ?int $size
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('size')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $size = null;

    /**
     *
     * @var ?bool $allowCameraUpload
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('allowCameraUpload')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $allowCameraUpload = null;

    /**
     *
     * @var ?bool $allowChannelAccess
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('allowChannelAccess')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $allowChannelAccess = null;

    /**
     *
     * @var ?bool $allowSharing
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('allowSharing')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $allowSharing = null;

    /**
     *
     * @var ?bool $allowSync
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('allowSync')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $allowSync = null;

    /**
     *
     * @var ?bool $allowTuners
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('allowTuners')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $allowTuners = null;

    /**
     *
     * @var ?bool $backgroundProcessing
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('backgroundProcessing')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $backgroundProcessing = null;

    /**
     *
     * @var ?bool $certificate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('certificate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $certificate = null;

    /**
     *
     * @var ?bool $companionProxy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('companionProxy')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $companionProxy = null;

    /**
     *
     * @var ?string $countryCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('countryCode')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $countryCode = null;

    /**
     *
     * @var ?string $diagnostics
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('diagnostics')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $diagnostics = null;

    /**
     *
     * @var ?bool $eventStream
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('eventStream')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $eventStream = null;

    /**
     *
     * @var ?string $friendlyName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('friendlyName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $friendlyName = null;

    /**
     *
     * @var ?int $livetv
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('livetv')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $livetv = null;

    /**
     *
     * @var ?string $machineIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('machineIdentifier')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $machineIdentifier = null;

    /**
     *
     * @var ?int $musicAnalysis
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('musicAnalysis')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $musicAnalysis = null;

    /**
     *
     * @var ?bool $myPlex
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('myPlex')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $myPlex = null;

    /**
     *
     * @var ?string $myPlexMappingState
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('myPlexMappingState')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $myPlexMappingState = null;

    /**
     *
     * @var ?string $myPlexSigninState
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('myPlexSigninState')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $myPlexSigninState = null;

    /**
     *
     * @var ?bool $myPlexSubscription
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('myPlexSubscription')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $myPlexSubscription = null;

    /**
     *
     * @var ?string $myPlexUsername
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('myPlexUsername')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $myPlexUsername = null;

    /**
     *
     * @var ?int $offlineTranscode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('offlineTranscode')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $offlineTranscode = null;

    /**
     *
     * @var ?string $ownerFeatures
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ownerFeatures')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $ownerFeatures = null;

    /**
     *
     * @var ?string $platform
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('platform')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $platform = null;

    /**
     *
     * @var ?string $platformVersion
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('platformVersion')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $platformVersion = null;

    /**
     *
     * @var ?bool $pluginHost
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pluginHost')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $pluginHost = null;

    /**
     *
     * @var ?bool $pushNotifications
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pushNotifications')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $pushNotifications = null;

    /**
     *
     * @var ?bool $readOnlyLibraries
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('readOnlyLibraries')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $readOnlyLibraries = null;

    /**
     *
     * @var ?int $streamingBrainABRVersion
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('streamingBrainABRVersion')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $streamingBrainABRVersion = null;

    /**
     *
     * @var ?int $streamingBrainVersion
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('streamingBrainVersion')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $streamingBrainVersion = null;

    /**
     *
     * @var ?bool $sync
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sync')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $sync = null;

    /**
     *
     * @var ?int $transcoderActiveVideoSessions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transcoderActiveVideoSessions')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $transcoderActiveVideoSessions = null;

    /**
     *
     * @var ?bool $transcoderAudio
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transcoderAudio')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $transcoderAudio = null;

    /**
     *
     * @var ?bool $transcoderLyrics
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transcoderLyrics')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $transcoderLyrics = null;

    /**
     *
     * @var ?bool $transcoderSubtitles
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transcoderSubtitles')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $transcoderSubtitles = null;

    /**
     *
     * @var ?bool $transcoderVideo
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transcoderVideo')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $transcoderVideo = null;

    /**
     *
     * @var ?string $transcoderVideoBitrates
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transcoderVideoBitrates')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $transcoderVideoBitrates = null;

    /**
     *
     * @var ?string $transcoderVideoQualities
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transcoderVideoQualities')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $transcoderVideoQualities = null;

    /**
     *
     * @var ?string $transcoderVideoResolutions
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transcoderVideoResolutions')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $transcoderVideoResolutions = null;

    /**
     *
     * @var ?int $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updatedAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $updatedAt = null;

    /**
     *
     * @var ?bool $updater
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updater')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $updater = null;

    /**
     *
     * @var ?string $version
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('version')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $version = null;

    /**
     *
     * @var ?bool $voiceSearch
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('voiceSearch')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $voiceSearch = null;

    /**
     * $mediaProvider
     *
     * @var ?array<MediaProvider> $mediaProvider
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('MediaProvider')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\MediaProvider>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $mediaProvider = null;

    /**
     * @param  ?int  $size
     * @param  ?bool  $allowCameraUpload
     * @param  ?bool  $allowChannelAccess
     * @param  ?bool  $allowSharing
     * @param  ?bool  $allowSync
     * @param  ?bool  $allowTuners
     * @param  ?bool  $backgroundProcessing
     * @param  ?bool  $certificate
     * @param  ?bool  $companionProxy
     * @param  ?string  $countryCode
     * @param  ?string  $diagnostics
     * @param  ?bool  $eventStream
     * @param  ?string  $friendlyName
     * @param  ?int  $livetv
     * @param  ?string  $machineIdentifier
     * @param  ?int  $musicAnalysis
     * @param  ?bool  $myPlex
     * @param  ?string  $myPlexMappingState
     * @param  ?string  $myPlexSigninState
     * @param  ?bool  $myPlexSubscription
     * @param  ?string  $myPlexUsername
     * @param  ?int  $offlineTranscode
     * @param  ?string  $ownerFeatures
     * @param  ?string  $platform
     * @param  ?string  $platformVersion
     * @param  ?bool  $pluginHost
     * @param  ?bool  $pushNotifications
     * @param  ?bool  $readOnlyLibraries
     * @param  ?int  $streamingBrainABRVersion
     * @param  ?int  $streamingBrainVersion
     * @param  ?bool  $sync
     * @param  ?int  $transcoderActiveVideoSessions
     * @param  ?bool  $transcoderAudio
     * @param  ?bool  $transcoderLyrics
     * @param  ?bool  $transcoderSubtitles
     * @param  ?bool  $transcoderVideo
     * @param  ?string  $transcoderVideoBitrates
     * @param  ?string  $transcoderVideoQualities
     * @param  ?string  $transcoderVideoResolutions
     * @param  ?int  $updatedAt
     * @param  ?bool  $updater
     * @param  ?string  $version
     * @param  ?bool  $voiceSearch
     * @param  ?array<MediaProvider>  $mediaProvider
     */
    public function __construct(?int $size = null, ?bool $allowCameraUpload = null, ?bool $allowChannelAccess = null, ?bool $allowSharing = null, ?bool $allowSync = null, ?bool $allowTuners = null, ?bool $backgroundProcessing = null, ?bool $certificate = null, ?bool $companionProxy = null, ?string $countryCode = null, ?string $diagnostics = null, ?bool $eventStream = null, ?string $friendlyName = null, ?int $livetv = null, ?string $machineIdentifier = null, ?int $musicAnalysis = null, ?bool $myPlex = null, ?string $myPlexMappingState = null, ?string $myPlexSigninState = null, ?bool $myPlexSubscription = null, ?string $myPlexUsername = null, ?int $offlineTranscode = null, ?string $ownerFeatures = null, ?string $platform = null, ?string $platformVersion = null, ?bool $pluginHost = null, ?bool $pushNotifications = null, ?bool $readOnlyLibraries = null, ?int $streamingBrainABRVersion = null, ?int $streamingBrainVersion = null, ?bool $sync = null, ?int $transcoderActiveVideoSessions = null, ?bool $transcoderAudio = null, ?bool $transcoderLyrics = null, ?bool $transcoderSubtitles = null, ?bool $transcoderVideo = null, ?string $transcoderVideoBitrates = null, ?string $transcoderVideoQualities = null, ?string $transcoderVideoResolutions = null, ?int $updatedAt = null, ?bool $updater = null, ?string $version = null, ?bool $voiceSearch = null, ?array $mediaProvider = null)
    {
        $this->size = $size;
        $this->allowCameraUpload = $allowCameraUpload;
        $this->allowChannelAccess = $allowChannelAccess;
        $this->allowSharing = $allowSharing;
        $this->allowSync = $allowSync;
        $this->allowTuners = $allowTuners;
        $this->backgroundProcessing = $backgroundProcessing;
        $this->certificate = $certificate;
        $this->companionProxy = $companionProxy;
        $this->countryCode = $countryCode;
        $this->diagnostics = $diagnostics;
        $this->eventStream = $eventStream;
        $this->friendlyName = $friendlyName;
        $this->livetv = $livetv;
        $this->machineIdentifier = $machineIdentifier;
        $this->musicAnalysis = $musicAnalysis;
        $this->myPlex = $myPlex;
        $this->myPlexMappingState = $myPlexMappingState;
        $this->myPlexSigninState = $myPlexSigninState;
        $this->myPlexSubscription = $myPlexSubscription;
        $this->myPlexUsername = $myPlexUsername;
        $this->offlineTranscode = $offlineTranscode;
        $this->ownerFeatures = $ownerFeatures;
        $this->platform = $platform;
        $this->platformVersion = $platformVersion;
        $this->pluginHost = $pluginHost;
        $this->pushNotifications = $pushNotifications;
        $this->readOnlyLibraries = $readOnlyLibraries;
        $this->streamingBrainABRVersion = $streamingBrainABRVersion;
        $this->streamingBrainVersion = $streamingBrainVersion;
        $this->sync = $sync;
        $this->transcoderActiveVideoSessions = $transcoderActiveVideoSessions;
        $this->transcoderAudio = $transcoderAudio;
        $this->transcoderLyrics = $transcoderLyrics;
        $this->transcoderSubtitles = $transcoderSubtitles;
        $this->transcoderVideo = $transcoderVideo;
        $this->transcoderVideoBitrates = $transcoderVideoBitrates;
        $this->transcoderVideoQualities = $transcoderVideoQualities;
        $this->transcoderVideoResolutions = $transcoderVideoResolutions;
        $this->updatedAt = $updatedAt;
        $this->updater = $updater;
        $this->version = $version;
        $this->voiceSearch = $voiceSearch;
        $this->mediaProvider = $mediaProvider;
    }
}