<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class GetMediaMetaDataPart
{
    /**
     * Unique part identifier.
     *
     * @var int $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public int $id;

    /**
     * Key to access this part.
     *
     * @var string $key
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('key')]
    public string $key;

    /**
     * Duration of the part in milliseconds.
     *
     * @var int $duration
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('duration')]
    public int $duration;

    /**
     * File path for the part.
     *
     * @var string $file
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('file')]
    public string $file;

    /**
     * File size in bytes.
     *
     * @var int $size
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('size')]
    public int $size;

    /**
     * Container format of the part.
     *
     * @var string $container
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('container')]
    public string $container;

    /**
     * Video profile for the part.
     *
     * @var string $videoProfile
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('videoProfile')]
    public string $videoProfile;

    /**
     * An array of streams for this part.
     *
     * @var array<GetMediaMetaDataStream> $stream
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('Stream')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetMediaMetaDataStream>')]
    public array $stream;

    /**
     * Indicates if the part is accessible.
     *
     * @var ?bool $accessible
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('accessible')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $accessible = null;

    /**
     * Indicates if the part exists.
     *
     * @var ?bool $exists
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('exists')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $exists = null;

    /**
     *
     * @var ?string $indexes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('indexes')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $indexes = null;

    /**
     * @param  int  $id
     * @param  string  $key
     * @param  int  $duration
     * @param  string  $file
     * @param  int  $size
     * @param  string  $container
     * @param  string  $videoProfile
     * @param  array<GetMediaMetaDataStream>  $stream
     * @param  ?bool  $accessible
     * @param  ?bool  $exists
     * @param  ?string  $indexes
     * @phpstan-pure
     */
    public function __construct(int $id, string $key, int $duration, string $file, int $size, string $container, string $videoProfile, array $stream, ?bool $accessible = null, ?bool $exists = null, ?string $indexes = null)
    {
        $this->id = $id;
        $this->key = $key;
        $this->duration = $duration;
        $this->file = $file;
        $this->size = $size;
        $this->container = $container;
        $this->videoProfile = $videoProfile;
        $this->stream = $stream;
        $this->accessible = $accessible;
        $this->exists = $exists;
        $this->indexes = $indexes;
    }
}