<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class GetMetadataChildrenDirectory
{
    /**
     *
     * @var ?int $leafCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('leafCount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $leafCount = null;

    /**
     *
     * @var ?string $thumb
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('thumb')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $thumb = null;

    /**
     *
     * @var ?int $viewedLeafCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('viewedLeafCount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $viewedLeafCount = null;

    /**
     *
     * @var ?string $key
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('key')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $key = null;

    /**
     *
     * @var ?string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $title = null;

    /**
     * @param  ?int  $leafCount
     * @param  ?string  $thumb
     * @param  ?int  $viewedLeafCount
     * @param  ?string  $key
     * @param  ?string  $title
     */
    public function __construct(?int $leafCount = null, ?string $thumb = null, ?int $viewedLeafCount = null, ?string $key = null, ?string $title = null)
    {
        $this->leafCount = $leafCount;
        $this->thumb = $thumb;
        $this->viewedLeafCount = $viewedLeafCount;
        $this->key = $key;
        $this->title = $title;
    }
}