<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;

use Brick\DateTime\LocalDate;
class GetMetaDataByRatingKeyMetadata
{
    /**
     *
     * @var ?string $ratingKey
     */
    #[\JMS\Serializer\Annotation\SerializedName('ratingKey')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $ratingKey = null;

    /**
     *
     * @var ?string $key
     */
    #[\JMS\Serializer\Annotation\SerializedName('key')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $key = null;

    /**
     *
     * @var ?string $guid
     */
    #[\JMS\Serializer\Annotation\SerializedName('guid')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $guid = null;

    /**
     *
     * @var ?string $studio
     */
    #[\JMS\Serializer\Annotation\SerializedName('studio')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $studio = null;

    /**
     *
     * @var ?string $type
     */
    #[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $type = null;

    /**
     *
     * @var ?string $title
     */
    #[\JMS\Serializer\Annotation\SerializedName('title')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $title = null;

    /**
     *
     * @var ?string $librarySectionTitle
     */
    #[\JMS\Serializer\Annotation\SerializedName('librarySectionTitle')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $librarySectionTitle = null;

    /**
     *
     * @var ?int $librarySectionID
     */
    #[\JMS\Serializer\Annotation\SerializedName('librarySectionID')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $librarySectionID = null;

    /**
     *
     * @var ?string $librarySectionKey
     */
    #[\JMS\Serializer\Annotation\SerializedName('librarySectionKey')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $librarySectionKey = null;

    /**
     *
     * @var ?string $contentRating
     */
    #[\JMS\Serializer\Annotation\SerializedName('contentRating')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $contentRating = null;

    /**
     *
     * @var ?string $summary
     */
    #[\JMS\Serializer\Annotation\SerializedName('summary')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $summary = null;

    /**
     *
     * @var ?float $rating
     */
    #[\JMS\Serializer\Annotation\SerializedName('rating')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?float $rating = null;

    /**
     *
     * @var ?float $audienceRating
     */
    #[\JMS\Serializer\Annotation\SerializedName('audienceRating')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?float $audienceRating = null;

    /**
     *
     * @var ?int $year
     */
    #[\JMS\Serializer\Annotation\SerializedName('year')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $year = null;

    /**
     *
     * @var ?string $tagline
     */
    #[\JMS\Serializer\Annotation\SerializedName('tagline')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $tagline = null;

    /**
     *
     * @var ?string $thumb
     */
    #[\JMS\Serializer\Annotation\SerializedName('thumb')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $thumb = null;

    /**
     *
     * @var ?string $art
     */
    #[\JMS\Serializer\Annotation\SerializedName('art')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $art = null;

    /**
     *
     * @var ?int $duration
     */
    #[\JMS\Serializer\Annotation\SerializedName('duration')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $duration = null;

    /**
     *
     * @var ?LocalDate $originallyAvailableAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('originallyAvailableAt')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?LocalDate $originallyAvailableAt = null;

    /**
     *
     * @var ?int $addedAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('addedAt')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $addedAt = null;

    /**
     *
     * @var ?int $updatedAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('updatedAt')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $updatedAt = null;

    /**
     *
     * @var ?string $audienceRatingImage
     */
    #[\JMS\Serializer\Annotation\SerializedName('audienceRatingImage')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $audienceRatingImage = null;

    /**
     *
     * @var ?string $hasPremiumPrimaryExtra
     */
    #[\JMS\Serializer\Annotation\SerializedName('hasPremiumPrimaryExtra')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $hasPremiumPrimaryExtra = null;

    /**
     *
     * @var ?string $ratingImage
     */
    #[\JMS\Serializer\Annotation\SerializedName('ratingImage')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $ratingImage = null;

    /**
     * $media
     *
     * @var ?array<GetMetaDataByRatingKeyMedia> $media
     */
    #[\JMS\Serializer\Annotation\SerializedName('Media')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetMetaDataByRatingKeyMedia>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $media = null;

    /**
     * $genre
     *
     * @var ?array<GetMetaDataByRatingKeyGenre> $genre
     */
    #[\JMS\Serializer\Annotation\SerializedName('Genre')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetMetaDataByRatingKeyGenre>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $genre = null;

    /**
     * $country
     *
     * @var ?array<GetMetaDataByRatingKeyCountry> $country
     */
    #[\JMS\Serializer\Annotation\SerializedName('Country')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetMetaDataByRatingKeyCountry>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $country = null;

    /**
     * $guids
     *
     * @var ?array<Guids> $guids
     */
    #[\JMS\Serializer\Annotation\SerializedName('Guid')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\Guids>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $guids = null;

    /**
     * $ratings
     *
     * @var ?array<Ratings> $ratings
     */
    #[\JMS\Serializer\Annotation\SerializedName('Rating')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\Ratings>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $ratings = null;

    /**
     * $director
     *
     * @var ?array<GetMetaDataByRatingKeyDirector> $director
     */
    #[\JMS\Serializer\Annotation\SerializedName('Director')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetMetaDataByRatingKeyDirector>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $director = null;

    /**
     * $writer
     *
     * @var ?array<GetMetaDataByRatingKeyWriter> $writer
     */
    #[\JMS\Serializer\Annotation\SerializedName('Writer')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetMetaDataByRatingKeyWriter>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $writer = null;

    /**
     * $role
     *
     * @var ?array<GetMetaDataByRatingKeyRole> $role
     */
    #[\JMS\Serializer\Annotation\SerializedName('Role')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetMetaDataByRatingKeyRole>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $role = null;

    /**
     * $producer
     *
     * @var ?array<Producer> $producer
     */
    #[\JMS\Serializer\Annotation\SerializedName('Producer')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\Producer>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $producer = null;

    /**
     * @param  ?string  $ratingKey
     * @param  ?string  $key
     * @param  ?string  $guid
     * @param  ?string  $studio
     * @param  ?string  $type
     * @param  ?string  $title
     * @param  ?string  $librarySectionTitle
     * @param  ?int  $librarySectionID
     * @param  ?string  $librarySectionKey
     * @param  ?string  $contentRating
     * @param  ?string  $summary
     * @param  ?float  $rating
     * @param  ?float  $audienceRating
     * @param  ?int  $year
     * @param  ?string  $tagline
     * @param  ?string  $thumb
     * @param  ?string  $art
     * @param  ?int  $duration
     * @param  ?LocalDate  $originallyAvailableAt
     * @param  ?int  $addedAt
     * @param  ?int  $updatedAt
     * @param  ?string  $audienceRatingImage
     * @param  ?string  $hasPremiumPrimaryExtra
     * @param  ?string  $ratingImage
     * @param  ?array<GetMetaDataByRatingKeyMedia>  $media
     * @param  ?array<GetMetaDataByRatingKeyGenre>  $genre
     * @param  ?array<GetMetaDataByRatingKeyCountry>  $country
     * @param  ?array<Guids>  $guids
     * @param  ?array<Ratings>  $ratings
     * @param  ?array<GetMetaDataByRatingKeyDirector>  $director
     * @param  ?array<GetMetaDataByRatingKeyWriter>  $writer
     * @param  ?array<GetMetaDataByRatingKeyRole>  $role
     * @param  ?array<Producer>  $producer
     */
    public function __construct(?string $ratingKey = null, ?string $key = null, ?string $guid = null, ?string $studio = null, ?string $type = null, ?string $title = null, ?string $librarySectionTitle = null, ?int $librarySectionID = null, ?string $librarySectionKey = null, ?string $contentRating = null, ?string $summary = null, ?float $rating = null, ?float $audienceRating = null, ?int $year = null, ?string $tagline = null, ?string $thumb = null, ?string $art = null, ?int $duration = null, ?LocalDate $originallyAvailableAt = null, ?int $addedAt = null, ?int $updatedAt = null, ?string $audienceRatingImage = null, ?string $hasPremiumPrimaryExtra = null, ?string $ratingImage = null, ?array $media = null, ?array $genre = null, ?array $country = null, ?array $guids = null, ?array $ratings = null, ?array $director = null, ?array $writer = null, ?array $role = null, ?array $producer = null)
    {
        $this->ratingKey = $ratingKey;
        $this->key = $key;
        $this->guid = $guid;
        $this->studio = $studio;
        $this->type = $type;
        $this->title = $title;
        $this->librarySectionTitle = $librarySectionTitle;
        $this->librarySectionID = $librarySectionID;
        $this->librarySectionKey = $librarySectionKey;
        $this->contentRating = $contentRating;
        $this->summary = $summary;
        $this->rating = $rating;
        $this->audienceRating = $audienceRating;
        $this->year = $year;
        $this->tagline = $tagline;
        $this->thumb = $thumb;
        $this->art = $art;
        $this->duration = $duration;
        $this->originallyAvailableAt = $originallyAvailableAt;
        $this->addedAt = $addedAt;
        $this->updatedAt = $updatedAt;
        $this->audienceRatingImage = $audienceRatingImage;
        $this->hasPremiumPrimaryExtra = $hasPremiumPrimaryExtra;
        $this->ratingImage = $ratingImage;
        $this->media = $media;
        $this->genre = $genre;
        $this->country = $country;
        $this->guids = $guids;
        $this->ratings = $ratings;
        $this->director = $director;
        $this->writer = $writer;
        $this->role = $role;
        $this->producer = $producer;
    }
}