<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class GetOnDeckMediaContainer
{
    /**
     *
     * @var ?float $size
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('size')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $size = null;

    /**
     *
     * @var ?bool $allowSync
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('allowSync')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $allowSync = null;

    /**
     *
     * @var ?string $identifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('identifier')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $identifier = null;

    /**
     *
     * @var ?string $mediaTagPrefix
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mediaTagPrefix')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $mediaTagPrefix = null;

    /**
     *
     * @var ?float $mediaTagVersion
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mediaTagVersion')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $mediaTagVersion = null;

    /**
     *
     * @var ?bool $mixedParents
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mixedParents')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $mixedParents = null;

    /**
     * $metadata
     *
     * @var ?array<GetOnDeckMetadata> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('Metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetOnDeckMetadata>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * @param  ?float  $size
     * @param  ?bool  $allowSync
     * @param  ?string  $identifier
     * @param  ?string  $mediaTagPrefix
     * @param  ?float  $mediaTagVersion
     * @param  ?bool  $mixedParents
     * @param  ?array<GetOnDeckMetadata>  $metadata
     * @phpstan-pure
     */
    public function __construct(?float $size = null, ?bool $allowSync = null, ?string $identifier = null, ?string $mediaTagPrefix = null, ?float $mediaTagVersion = null, ?bool $mixedParents = null, ?array $metadata = null)
    {
        $this->size = $size;
        $this->allowSync = $allowSync;
        $this->identifier = $identifier;
        $this->mediaTagPrefix = $mediaTagPrefix;
        $this->mediaTagVersion = $mediaTagVersion;
        $this->mixedParents = $mixedParents;
        $this->metadata = $metadata;
    }
}