<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class GetPlaylistContentsMedia
{
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $id = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('duration')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $duration = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('bitrate')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $bitrate = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('width')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $width = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('height')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $height = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('aspectRatio')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $aspectRatio = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('audioChannels')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $audioChannels = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('audioCodec')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $audioCodec = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('videoCodec')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $videoCodec = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('videoResolution')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $videoResolution = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('container')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $container = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('videoFrameRate')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $videoFrameRate = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('optimizedForStreaming')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $optimizedForStreaming = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('audioProfile')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $audioProfile = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('has64bitOffsets')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $has64bitOffsets = null;
    
	#[\JMS\Serializer\Annotation\SerializedName('videoProfile')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $videoProfile = null;
    
    /**
     * $part
     * 
     * @var ?array<\LukeHagar\Plex_API\Models\Operations\GetPlaylistContentsPart> $part
     */
	#[\JMS\Serializer\Annotation\SerializedName('Part')]
    #[\JMS\Serializer\Annotation\Type('array<LukeHagar\Plex_API\Models\Operations\GetPlaylistContentsPart>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $part = null;
    
	public function __construct()
	{
		$this->id = null;
		$this->duration = null;
		$this->bitrate = null;
		$this->width = null;
		$this->height = null;
		$this->aspectRatio = null;
		$this->audioChannels = null;
		$this->audioCodec = null;
		$this->videoCodec = null;
		$this->videoResolution = null;
		$this->container = null;
		$this->videoFrameRate = null;
		$this->optimizedForStreaming = null;
		$this->audioProfile = null;
		$this->has64bitOffsets = null;
		$this->videoProfile = null;
		$this->part = null;
	}
}
