<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class GetPlaylistsMetadata
{
    /**
     *
     * @var ?string $ratingKey
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ratingKey')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $ratingKey = null;

    /**
     *
     * @var ?string $key
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('key')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $key = null;

    /**
     *
     * @var ?string $guid
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('guid')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $guid = null;

    /**
     *
     * @var ?string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $type = null;

    /**
     *
     * @var ?string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $title = null;

    /**
     *
     * @var ?string $summary
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('summary')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $summary = null;

    /**
     *
     * @var ?bool $smart
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('smart')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $smart = null;

    /**
     *
     * @var ?string $playlistType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('playlistType')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $playlistType = null;

    /**
     *
     * @var ?string $composite
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('composite')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $composite = null;

    /**
     *
     * @var ?string $icon
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('icon')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $icon = null;

    /**
     *
     * @var ?int $viewCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('viewCount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $viewCount = null;

    /**
     *
     * @var ?int $lastViewedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastViewedAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $lastViewedAt = null;

    /**
     *
     * @var ?int $duration
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('duration')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $duration = null;

    /**
     *
     * @var ?int $leafCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('leafCount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $leafCount = null;

    /**
     *
     * @var ?int $addedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('addedAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $addedAt = null;

    /**
     *
     * @var ?int $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updatedAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $updatedAt = null;

    /**
     * @param  ?string  $ratingKey
     * @param  ?string  $key
     * @param  ?string  $guid
     * @param  ?string  $type
     * @param  ?string  $title
     * @param  ?string  $summary
     * @param  ?bool  $smart
     * @param  ?string  $playlistType
     * @param  ?string  $composite
     * @param  ?string  $icon
     * @param  ?int  $viewCount
     * @param  ?int  $lastViewedAt
     * @param  ?int  $duration
     * @param  ?int  $leafCount
     * @param  ?int  $addedAt
     * @param  ?int  $updatedAt
     * @phpstan-pure
     */
    public function __construct(?string $ratingKey = null, ?string $key = null, ?string $guid = null, ?string $type = null, ?string $title = null, ?string $summary = null, ?bool $smart = null, ?string $playlistType = null, ?string $composite = null, ?string $icon = null, ?int $viewCount = null, ?int $lastViewedAt = null, ?int $duration = null, ?int $leafCount = null, ?int $addedAt = null, ?int $updatedAt = null)
    {
        $this->ratingKey = $ratingKey;
        $this->key = $key;
        $this->guid = $guid;
        $this->type = $type;
        $this->title = $title;
        $this->summary = $summary;
        $this->smart = $smart;
        $this->playlistType = $playlistType;
        $this->composite = $composite;
        $this->icon = $icon;
        $this->viewCount = $viewCount;
        $this->lastViewedAt = $lastViewedAt;
        $this->duration = $duration;
        $this->leafCount = $leafCount;
        $this->addedAt = $addedAt;
        $this->updatedAt = $updatedAt;
    }
}