<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


/** GetResourcesStatisticsResponseBody - Resource Statistics */
class GetResourcesStatisticsResponseBody
{
    #[\JMS\Serializer\Annotation\SerializedName('MediaContainer')]
    #[\JMS\Serializer\Annotation\Type('LukeHagar\Plex_API\Models\Operations\GetResourcesStatisticsMediaContainer')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?GetResourcesStatisticsMediaContainer $mediaContainer = null;

    public function __construct()
    {
        $this->mediaContainer = null;
    }
}