<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;

use LukeHagar\Plex_API\Utils\SpeakeasyMetadata;
class GetResizedPhotoRequest
{
    /**
     * The width for the resized photo
     *
     * @var float $width
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=width')]
    public float $width;

    /**
     * The height for the resized photo
     *
     * @var float $height
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=height')]
    public float $height;

    /**
     * The opacity for the resized photo
     *
     * @var int $opacity
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=opacity')]
    public int $opacity;

    /**
     * The width for the resized photo
     *
     * @var float $blur
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=blur')]
    public float $blur;

    /**
     * images are always scaled proportionally. A value of '1' in minSize will make the smaller native dimension the dimension resized against.
     *
     * @var \LukeHagar\Plex_API\Models\Operations\MinSize $minSize
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=minSize')]
    public MinSize $minSize;

    /**
     * allow images to be resized beyond native dimensions.
     *
     * @var \LukeHagar\Plex_API\Models\Operations\Upscale $upscale
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=upscale')]
    public Upscale $upscale;

    /**
     * path to image within Plex
     *
     * @var string $url
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=url')]
    public string $url;

    public function __construct()
    {
        $this->width = 0;
        $this->height = 0;
        $this->opacity = 0;
        $this->blur = 0;
        $this->minSize = \LukeHagar\Plex_API\Models\Operations\MinSize::Zero;
        $this->upscale = \LukeHagar\Plex_API\Models\Operations\Upscale::Zero;
        $this->url = '';
    }
}