<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class GetRecentlyAddedFieldType
{
    /**
     *
     * @var string $type
     */
    #[\JMS\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     * $operator
     *
     * @var array<GetRecentlyAddedOperator> $operator
     */
    #[\JMS\Serializer\Annotation\SerializedName('Operator')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetRecentlyAddedOperator>')]
    public array $operator;

    /**
     * @param  string  $type
     * @param  array<GetRecentlyAddedOperator>  $operator
     */
    public function __construct(string $type, array $operator)
    {
        $this->type = $type;
        $this->operator = $operator;
    }
}