<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class GetRecentlyAddedLibraryMetadata
{
    /**
     *
     * @var ?bool $allowSync
     */
    #[\JMS\Serializer\Annotation\SerializedName('allowSync')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?bool $allowSync = null;

    /**
     *
     * @var ?float $librarySectionID
     */
    #[\JMS\Serializer\Annotation\SerializedName('librarySectionID')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?float $librarySectionID = null;

    /**
     *
     * @var ?string $librarySectionTitle
     */
    #[\JMS\Serializer\Annotation\SerializedName('librarySectionTitle')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $librarySectionTitle = null;

    /**
     *
     * @var ?string $librarySectionUUID
     */
    #[\JMS\Serializer\Annotation\SerializedName('librarySectionUUID')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $librarySectionUUID = null;

    /**
     *
     * @var ?float $ratingKey
     */
    #[\JMS\Serializer\Annotation\SerializedName('ratingKey')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?float $ratingKey = null;

    /**
     *
     * @var ?string $key
     */
    #[\JMS\Serializer\Annotation\SerializedName('key')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $key = null;

    /**
     *
     * @var ?string $guid
     */
    #[\JMS\Serializer\Annotation\SerializedName('guid')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $guid = null;

    /**
     *
     * @var ?string $studio
     */
    #[\JMS\Serializer\Annotation\SerializedName('studio')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $studio = null;

    /**
     *
     * @var ?string $type
     */
    #[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $type = null;

    /**
     *
     * @var ?string $title
     */
    #[\JMS\Serializer\Annotation\SerializedName('title')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $title = null;

    /**
     *
     * @var ?string $contentRating
     */
    #[\JMS\Serializer\Annotation\SerializedName('contentRating')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $contentRating = null;

    /**
     *
     * @var ?string $summary
     */
    #[\JMS\Serializer\Annotation\SerializedName('summary')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $summary = null;

    /**
     *
     * @var ?float $rating
     */
    #[\JMS\Serializer\Annotation\SerializedName('rating')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?float $rating = null;

    /**
     *
     * @var ?float $audienceRating
     */
    #[\JMS\Serializer\Annotation\SerializedName('audienceRating')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?float $audienceRating = null;

    /**
     *
     * @var ?float $year
     */
    #[\JMS\Serializer\Annotation\SerializedName('year')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?float $year = null;

    /**
     *
     * @var ?string $tagline
     */
    #[\JMS\Serializer\Annotation\SerializedName('tagline')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $tagline = null;

    /**
     *
     * @var ?string $thumb
     */
    #[\JMS\Serializer\Annotation\SerializedName('thumb')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $thumb = null;

    /**
     *
     * @var ?string $art
     */
    #[\JMS\Serializer\Annotation\SerializedName('art')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $art = null;

    /**
     *
     * @var ?float $duration
     */
    #[\JMS\Serializer\Annotation\SerializedName('duration')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?float $duration = null;

    /**
     *
     * @var ?\DateTime $originallyAvailableAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('originallyAvailableAt')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $originallyAvailableAt = null;

    /**
     *
     * @var ?float $addedAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('addedAt')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?float $addedAt = null;

    /**
     *
     * @var ?float $updatedAt
     */
    #[\JMS\Serializer\Annotation\SerializedName('updatedAt')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?float $updatedAt = null;

    /**
     *
     * @var ?string $audienceRatingImage
     */
    #[\JMS\Serializer\Annotation\SerializedName('audienceRatingImage')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $audienceRatingImage = null;

    /**
     *
     * @var ?string $chapterSource
     */
    #[\JMS\Serializer\Annotation\SerializedName('chapterSource')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $chapterSource = null;

    /**
     *
     * @var ?string $primaryExtraKey
     */
    #[\JMS\Serializer\Annotation\SerializedName('primaryExtraKey')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $primaryExtraKey = null;

    /**
     *
     * @var ?string $ratingImage
     */
    #[\JMS\Serializer\Annotation\SerializedName('ratingImage')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $ratingImage = null;

    /**
     * $media
     *
     * @var ?array<GetRecentlyAddedLibraryMedia> $media
     */
    #[\JMS\Serializer\Annotation\SerializedName('Media')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetRecentlyAddedLibraryMedia>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $media = null;

    /**
     * $genre
     *
     * @var ?array<GetRecentlyAddedLibraryGenre> $genre
     */
    #[\JMS\Serializer\Annotation\SerializedName('Genre')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetRecentlyAddedLibraryGenre>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $genre = null;

    /**
     * $director
     *
     * @var ?array<GetRecentlyAddedLibraryDirector> $director
     */
    #[\JMS\Serializer\Annotation\SerializedName('Director')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetRecentlyAddedLibraryDirector>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $director = null;

    /**
     * $writer
     *
     * @var ?array<GetRecentlyAddedLibraryWriter> $writer
     */
    #[\JMS\Serializer\Annotation\SerializedName('Writer')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetRecentlyAddedLibraryWriter>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $writer = null;

    /**
     * $country
     *
     * @var ?array<GetRecentlyAddedLibraryCountry> $country
     */
    #[\JMS\Serializer\Annotation\SerializedName('Country')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetRecentlyAddedLibraryCountry>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $country = null;

    /**
     * $role
     *
     * @var ?array<GetRecentlyAddedLibraryRole> $role
     */
    #[\JMS\Serializer\Annotation\SerializedName('Role')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetRecentlyAddedLibraryRole>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $role = null;

    /**
     * @param  ?bool  $allowSync
     * @param  ?float  $librarySectionID
     * @param  ?string  $librarySectionTitle
     * @param  ?string  $librarySectionUUID
     * @param  ?float  $ratingKey
     * @param  ?string  $key
     * @param  ?string  $guid
     * @param  ?string  $studio
     * @param  ?string  $type
     * @param  ?string  $title
     * @param  ?string  $contentRating
     * @param  ?string  $summary
     * @param  ?float  $rating
     * @param  ?float  $audienceRating
     * @param  ?float  $year
     * @param  ?string  $tagline
     * @param  ?string  $thumb
     * @param  ?string  $art
     * @param  ?float  $duration
     * @param  ?\DateTime  $originallyAvailableAt
     * @param  ?float  $addedAt
     * @param  ?float  $updatedAt
     * @param  ?string  $audienceRatingImage
     * @param  ?string  $chapterSource
     * @param  ?string  $primaryExtraKey
     * @param  ?string  $ratingImage
     * @param  ?array<GetRecentlyAddedLibraryMedia>  $media
     * @param  ?array<GetRecentlyAddedLibraryGenre>  $genre
     * @param  ?array<GetRecentlyAddedLibraryDirector>  $director
     * @param  ?array<GetRecentlyAddedLibraryWriter>  $writer
     * @param  ?array<GetRecentlyAddedLibraryCountry>  $country
     * @param  ?array<GetRecentlyAddedLibraryRole>  $role
     */
    public function __construct(?bool $allowSync = null, ?float $librarySectionID = null, ?string $librarySectionTitle = null, ?string $librarySectionUUID = null, ?float $ratingKey = null, ?string $key = null, ?string $guid = null, ?string $studio = null, ?string $type = null, ?string $title = null, ?string $contentRating = null, ?string $summary = null, ?float $rating = null, ?float $audienceRating = null, ?float $year = null, ?string $tagline = null, ?string $thumb = null, ?string $art = null, ?float $duration = null, ?\DateTime $originallyAvailableAt = null, ?float $addedAt = null, ?float $updatedAt = null, ?string $audienceRatingImage = null, ?string $chapterSource = null, ?string $primaryExtraKey = null, ?string $ratingImage = null, ?array $media = null, ?array $genre = null, ?array $director = null, ?array $writer = null, ?array $country = null, ?array $role = null)
    {
        $this->allowSync = $allowSync;
        $this->librarySectionID = $librarySectionID;
        $this->librarySectionTitle = $librarySectionTitle;
        $this->librarySectionUUID = $librarySectionUUID;
        $this->ratingKey = $ratingKey;
        $this->key = $key;
        $this->guid = $guid;
        $this->studio = $studio;
        $this->type = $type;
        $this->title = $title;
        $this->contentRating = $contentRating;
        $this->summary = $summary;
        $this->rating = $rating;
        $this->audienceRating = $audienceRating;
        $this->year = $year;
        $this->tagline = $tagline;
        $this->thumb = $thumb;
        $this->art = $art;
        $this->duration = $duration;
        $this->originallyAvailableAt = $originallyAvailableAt;
        $this->addedAt = $addedAt;
        $this->updatedAt = $updatedAt;
        $this->audienceRatingImage = $audienceRatingImage;
        $this->chapterSource = $chapterSource;
        $this->primaryExtraKey = $primaryExtraKey;
        $this->ratingImage = $ratingImage;
        $this->media = $media;
        $this->genre = $genre;
        $this->director = $director;
        $this->writer = $writer;
        $this->country = $country;
        $this->role = $role;
    }
}