<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


/**
 * GetRecentlyAddedLibraryMediaContainer - The Meta object is only included in the response if the `includeMeta` parameter is set to `1`.
 *
 *
 */
class GetRecentlyAddedLibraryMediaContainer
{
    /**
     * $type
     *
     * @var ?array<GetRecentlyAddedLibraryType> $type
     */
    #[\JMS\Serializer\Annotation\SerializedName('Type')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetRecentlyAddedLibraryType>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $type = null;

    /**
     * $fieldType
     *
     * @var ?array<FieldType> $fieldType
     */
    #[\JMS\Serializer\Annotation\SerializedName('FieldType')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\FieldType>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $fieldType = null;

    /**
     *
     * @var ?float $size
     */
    #[\JMS\Serializer\Annotation\SerializedName('size')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?float $size = null;

    /**
     *
     * @var ?bool $allowSync
     */
    #[\JMS\Serializer\Annotation\SerializedName('allowSync')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?bool $allowSync = null;

    /**
     *
     * @var ?string $identifier
     */
    #[\JMS\Serializer\Annotation\SerializedName('identifier')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $identifier = null;

    /**
     *
     * @var ?string $mediaTagPrefix
     */
    #[\JMS\Serializer\Annotation\SerializedName('mediaTagPrefix')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $mediaTagPrefix = null;

    /**
     *
     * @var ?float $mediaTagVersion
     */
    #[\JMS\Serializer\Annotation\SerializedName('mediaTagVersion')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?float $mediaTagVersion = null;

    /**
     *
     * @var ?bool $mixedParents
     */
    #[\JMS\Serializer\Annotation\SerializedName('mixedParents')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?bool $mixedParents = null;

    /**
     * $metadata
     *
     * @var ?array<GetRecentlyAddedLibraryMetadata> $metadata
     */
    #[\JMS\Serializer\Annotation\SerializedName('Metadata')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetRecentlyAddedLibraryMetadata>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $metadata = null;

    /**
     * @param  ?array<GetRecentlyAddedLibraryType>  $type
     * @param  ?array<FieldType>  $fieldType
     * @param  ?float  $size
     * @param  ?bool  $allowSync
     * @param  ?string  $identifier
     * @param  ?string  $mediaTagPrefix
     * @param  ?float  $mediaTagVersion
     * @param  ?bool  $mixedParents
     * @param  ?array<GetRecentlyAddedLibraryMetadata>  $metadata
     */
    public function __construct(?array $type = null, ?array $fieldType = null, ?float $size = null, ?bool $allowSync = null, ?string $identifier = null, ?string $mediaTagPrefix = null, ?float $mediaTagVersion = null, ?bool $mixedParents = null, ?array $metadata = null)
    {
        $this->type = $type;
        $this->fieldType = $fieldType;
        $this->size = $size;
        $this->allowSync = $allowSync;
        $this->identifier = $identifier;
        $this->mediaTagPrefix = $mediaTagPrefix;
        $this->mediaTagVersion = $mediaTagVersion;
        $this->mixedParents = $mixedParents;
        $this->metadata = $metadata;
    }
}