<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class GetRecentlyAddedMetadata
{
    #[\JMS\Serializer\Annotation\SerializedName('allowSync')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $allowSync = null;

    #[\JMS\Serializer\Annotation\SerializedName('librarySectionID')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $librarySectionID = null;

    #[\JMS\Serializer\Annotation\SerializedName('librarySectionTitle')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $librarySectionTitle = null;

    #[\JMS\Serializer\Annotation\SerializedName('librarySectionUUID')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $librarySectionUUID = null;

    #[\JMS\Serializer\Annotation\SerializedName('ratingKey')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $ratingKey = null;

    #[\JMS\Serializer\Annotation\SerializedName('key')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $key = null;

    #[\JMS\Serializer\Annotation\SerializedName('guid')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $guid = null;

    #[\JMS\Serializer\Annotation\SerializedName('studio')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $studio = null;

    #[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $type = null;

    #[\JMS\Serializer\Annotation\SerializedName('title')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $title = null;

    #[\JMS\Serializer\Annotation\SerializedName('contentRating')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $contentRating = null;

    #[\JMS\Serializer\Annotation\SerializedName('summary')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $summary = null;

    #[\JMS\Serializer\Annotation\SerializedName('rating')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $rating = null;

    #[\JMS\Serializer\Annotation\SerializedName('audienceRating')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $audienceRating = null;

    #[\JMS\Serializer\Annotation\SerializedName('year')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $year = null;

    #[\JMS\Serializer\Annotation\SerializedName('tagline')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $tagline = null;

    #[\JMS\Serializer\Annotation\SerializedName('thumb')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $thumb = null;

    #[\JMS\Serializer\Annotation\SerializedName('art')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $art = null;

    #[\JMS\Serializer\Annotation\SerializedName('duration')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $duration = null;

    #[\JMS\Serializer\Annotation\SerializedName('originallyAvailableAt')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $originallyAvailableAt = null;

    #[\JMS\Serializer\Annotation\SerializedName('addedAt')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $addedAt = null;

    #[\JMS\Serializer\Annotation\SerializedName('updatedAt')]
    #[\JMS\Serializer\Annotation\Type('float')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?float $updatedAt = null;

    #[\JMS\Serializer\Annotation\SerializedName('audienceRatingImage')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $audienceRatingImage = null;

    #[\JMS\Serializer\Annotation\SerializedName('chapterSource')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $chapterSource = null;

    #[\JMS\Serializer\Annotation\SerializedName('primaryExtraKey')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $primaryExtraKey = null;

    #[\JMS\Serializer\Annotation\SerializedName('ratingImage')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $ratingImage = null;

    /**
     * $media
     *
     * @var ?array<\LukeHagar\Plex_API\Models\Operations\Media> $media
     */
    #[\JMS\Serializer\Annotation\SerializedName('Media')]
    #[\JMS\Serializer\Annotation\Type('array<LukeHagar\Plex_API\Models\Operations\Media>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $media = null;

    /**
     * $genre
     *
     * @var ?array<\LukeHagar\Plex_API\Models\Operations\Genre> $genre
     */
    #[\JMS\Serializer\Annotation\SerializedName('Genre')]
    #[\JMS\Serializer\Annotation\Type('array<LukeHagar\Plex_API\Models\Operations\Genre>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $genre = null;

    /**
     * $director
     *
     * @var ?array<\LukeHagar\Plex_API\Models\Operations\Director> $director
     */
    #[\JMS\Serializer\Annotation\SerializedName('Director')]
    #[\JMS\Serializer\Annotation\Type('array<LukeHagar\Plex_API\Models\Operations\Director>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $director = null;

    /**
     * $writer
     *
     * @var ?array<\LukeHagar\Plex_API\Models\Operations\Writer> $writer
     */
    #[\JMS\Serializer\Annotation\SerializedName('Writer')]
    #[\JMS\Serializer\Annotation\Type('array<LukeHagar\Plex_API\Models\Operations\Writer>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $writer = null;

    /**
     * $country
     *
     * @var ?array<\LukeHagar\Plex_API\Models\Operations\Country> $country
     */
    #[\JMS\Serializer\Annotation\SerializedName('Country')]
    #[\JMS\Serializer\Annotation\Type('array<LukeHagar\Plex_API\Models\Operations\Country>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $country = null;

    /**
     * $role
     *
     * @var ?array<\LukeHagar\Plex_API\Models\Operations\Role> $role
     */
    #[\JMS\Serializer\Annotation\SerializedName('Role')]
    #[\JMS\Serializer\Annotation\Type('array<LukeHagar\Plex_API\Models\Operations\Role>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $role = null;

    public function __construct()
    {
        $this->allowSync = null;
        $this->librarySectionID = null;
        $this->librarySectionTitle = null;
        $this->librarySectionUUID = null;
        $this->ratingKey = null;
        $this->key = null;
        $this->guid = null;
        $this->studio = null;
        $this->type = null;
        $this->title = null;
        $this->contentRating = null;
        $this->summary = null;
        $this->rating = null;
        $this->audienceRating = null;
        $this->year = null;
        $this->tagline = null;
        $this->thumb = null;
        $this->art = null;
        $this->duration = null;
        $this->originallyAvailableAt = null;
        $this->addedAt = null;
        $this->updatedAt = null;
        $this->audienceRatingImage = null;
        $this->chapterSource = null;
        $this->primaryExtraKey = null;
        $this->ratingImage = null;
        $this->media = null;
        $this->genre = null;
        $this->director = null;
        $this->writer = null;
        $this->country = null;
        $this->role = null;
    }
}