<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


/** GetRecentlyAddedLibraryResponseBody - The recently added content */
class GetRecentlyAddedLibraryResponseBody
{
    /**
     *
     * @var ?GetRecentlyAddedLibraryMediaContainer $mediaContainer
     */
    #[\JMS\Serializer\Annotation\SerializedName('MediaContainer')]
    #[\JMS\Serializer\Annotation\Type('\LukeHagar\Plex_API\Models\Operations\GetRecentlyAddedLibraryMediaContainer|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?GetRecentlyAddedLibraryMediaContainer $mediaContainer = null;

    /**
     * @param  ?GetRecentlyAddedLibraryMediaContainer  $mediaContainer
     */
    public function __construct(?GetRecentlyAddedLibraryMediaContainer $mediaContainer = null)
    {
        $this->mediaContainer = $mediaContainer;
    }
}