<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;

use LukeHagar\Plex_API\Utils\SpeakeasyMetadata;
class GetSearchResultsRequest
{
    /**
     * The search query string to use
     *
     * @var string $query
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=query')]
    public string $query;

    /**
     * @param  string  $query
     * @phpstan-pure
     */
    public function __construct(string $query)
    {
        $this->query = $query;
    }
}