<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class GetSessionsStream
{
    /**
     *
     * @var ?string $albumGain
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('albumGain')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $albumGain = null;

    /**
     *
     * @var ?string $albumPeak
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('albumPeak')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $albumPeak = null;

    /**
     *
     * @var ?string $albumRange
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('albumRange')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $albumRange = null;

    /**
     *
     * @var ?string $audioChannelLayout
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('audioChannelLayout')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $audioChannelLayout = null;

    /**
     *
     * @var ?int $bitDepth
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bitDepth')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $bitDepth = null;

    /**
     *
     * @var ?int $bitrate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bitrate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $bitrate = null;

    /**
     *
     * @var ?int $channels
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('channels')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $channels = null;

    /**
     *
     * @var ?string $codec
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('codec')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $codec = null;

    /**
     *
     * @var ?string $displayTitle
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('displayTitle')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $displayTitle = null;

    /**
     *
     * @var ?string $extendedDisplayTitle
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('extendedDisplayTitle')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $extendedDisplayTitle = null;

    /**
     *
     * @var ?string $gain
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('gain')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $gain = null;

    /**
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     *
     * @var ?int $index
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('index')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $index = null;

    /**
     *
     * @var ?string $loudness
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('loudness')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $loudness = null;

    /**
     *
     * @var ?string $lra
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lra')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $lra = null;

    /**
     *
     * @var ?string $peak
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('peak')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $peak = null;

    /**
     *
     * @var ?int $samplingRate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('samplingRate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $samplingRate = null;

    /**
     *
     * @var ?bool $selected
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('selected')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $selected = null;

    /**
     *
     * @var ?int $streamType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('streamType')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $streamType = null;

    /**
     *
     * @var ?string $location
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('location')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $location = null;

    /**
     * @param  ?string  $albumGain
     * @param  ?string  $albumPeak
     * @param  ?string  $albumRange
     * @param  ?string  $audioChannelLayout
     * @param  ?int  $bitDepth
     * @param  ?int  $bitrate
     * @param  ?int  $channels
     * @param  ?string  $codec
     * @param  ?string  $displayTitle
     * @param  ?string  $extendedDisplayTitle
     * @param  ?string  $gain
     * @param  ?string  $id
     * @param  ?int  $index
     * @param  ?string  $loudness
     * @param  ?string  $lra
     * @param  ?string  $peak
     * @param  ?int  $samplingRate
     * @param  ?bool  $selected
     * @param  ?int  $streamType
     * @param  ?string  $location
     * @phpstan-pure
     */
    public function __construct(?string $albumGain = null, ?string $albumPeak = null, ?string $albumRange = null, ?string $audioChannelLayout = null, ?int $bitDepth = null, ?int $bitrate = null, ?int $channels = null, ?string $codec = null, ?string $displayTitle = null, ?string $extendedDisplayTitle = null, ?string $gain = null, ?string $id = null, ?int $index = null, ?string $loudness = null, ?string $lra = null, ?string $peak = null, ?int $samplingRate = null, ?bool $selected = null, ?int $streamType = null, ?string $location = null)
    {
        $this->albumGain = $albumGain;
        $this->albumPeak = $albumPeak;
        $this->albumRange = $albumRange;
        $this->audioChannelLayout = $audioChannelLayout;
        $this->bitDepth = $bitDepth;
        $this->bitrate = $bitrate;
        $this->channels = $channels;
        $this->codec = $codec;
        $this->displayTitle = $displayTitle;
        $this->extendedDisplayTitle = $extendedDisplayTitle;
        $this->gain = $gain;
        $this->id = $id;
        $this->index = $index;
        $this->loudness = $loudness;
        $this->lra = $lra;
        $this->peak = $peak;
        $this->samplingRate = $samplingRate;
        $this->selected = $selected;
        $this->streamType = $streamType;
        $this->location = $location;
    }
}