<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;

use LukeHagar\Plex_API\Utils\SpeakeasyMetadata;
class GetSessionHistoryRequest
{
    /**
     * Sorts the results by the specified field followed by the direction (asc, desc)
     *
     *
     *
     * @var ?string $sort
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=sort')]
    public ?string $sort = null;

    /**
     * Filter results by those that are related to a specific users id
     *
     *
     *
     * @var ?int $accountId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=accountId')]
    public ?int $accountId = null;

    /**
     * Filters content by field and direction/equality
     *
     * (Unknown if viewedAt is the only supported column)
     *
     *
     * @var ?\LukeHagar\Plex_API\Models\Operations\Filter $filter
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=filter')]
    public ?Filter $filter = null;

    /**
     * Filters the results based on the id of a valid library section
     *
     *
     *
     * @var ?int $librarySectionID
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=librarySectionID')]
    public ?int $librarySectionID = null;

    public function __construct()
    {
        $this->sort = null;
        $this->accountId = null;
        $this->filter = null;
        $this->librarySectionID = null;
    }
}