<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


/** GetServerIdentityResponseBody - The Server Identity information */
class GetServerIdentityResponseBody
{
    #[\JMS\Serializer\Annotation\SerializedName('MediaContainer')]
    #[\JMS\Serializer\Annotation\Type('LukeHagar\Plex_API\Models\Operations\GetServerIdentityMediaContainer')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?GetServerIdentityMediaContainer $mediaContainer = null;

    public function __construct()
    {
        $this->mediaContainer = null;
    }
}