<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;

use LukeHagar\Plex_API\Utils\SpeakeasyMetadata;
class GetSessionHistoryRequest
{
    /**
     * Sorts the results by the specified field followed by the direction (asc, desc)
     *
     *
     *
     * @var ?string $sort
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=sort')]
    public ?string $sort = null;

    /**
     * Filter results by those that are related to a specific users id
     *
     *
     *
     * @var ?int $accountId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=accountId')]
    public ?int $accountId = null;

    /**
     * Filters content by field and direction/equality
     *
     * (Unknown if viewedAt is the only supported column)
     *
     *
     * @var ?Filter $filter
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=filter')]
    public ?Filter $filter = null;

    /**
     * Filters the results based on the id of a valid library section
     *
     *
     *
     * @var ?int $librarySectionID
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=librarySectionID')]
    public ?int $librarySectionID = null;

    /**
     * @param  ?string  $sort
     * @param  ?int  $accountId
     * @param  ?Filter  $filter
     * @param  ?int  $librarySectionID
     */
    public function __construct(?string $sort = null, ?int $accountId = null, ?Filter $filter = null, ?int $librarySectionID = null)
    {
        $this->sort = $sort;
        $this->accountId = $accountId;
        $this->filter = $filter;
        $this->librarySectionID = $librarySectionID;
    }
}