<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class GetSearchAllLibrariesImage
{
    /**
     *
     * @var string $alt
     */
    #[\JMS\Serializer\Annotation\SerializedName('alt')]
    public string $alt;

    /**
     *
     * @var GetSearchAllLibrariesLibraryType $type
     */
    #[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('\LukeHagar\Plex_API\Models\Operations\GetSearchAllLibrariesLibraryType')]
    public GetSearchAllLibrariesLibraryType $type;

    /**
     *
     * @var string $url
     */
    #[\JMS\Serializer\Annotation\SerializedName('url')]
    public string $url;

    /**
     * @param  string  $alt
     * @param  GetSearchAllLibrariesLibraryType  $type
     * @param  string  $url
     */
    public function __construct(string $alt, GetSearchAllLibrariesLibraryType $type, string $url)
    {
        $this->alt = $alt;
        $this->type = $type;
        $this->url = $url;
    }
}