<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class GetServerIdentityMediaContainer
{
    /**
     *
     * @var ?float $size
     */
    #[\JMS\Serializer\Annotation\SerializedName('size')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?float $size = null;

    /**
     *
     * @var ?bool $claimed
     */
    #[\JMS\Serializer\Annotation\SerializedName('claimed')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?bool $claimed = null;

    /**
     *
     * @var ?string $machineIdentifier
     */
    #[\JMS\Serializer\Annotation\SerializedName('machineIdentifier')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $machineIdentifier = null;

    /**
     *
     * @var ?string $version
     */
    #[\JMS\Serializer\Annotation\SerializedName('version')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $version = null;

    /**
     * @param  ?float  $size
     * @param  ?bool  $claimed
     * @param  ?string  $machineIdentifier
     * @param  ?string  $version
     */
    public function __construct(?float $size = null, ?bool $claimed = null, ?string $machineIdentifier = null, ?string $version = null)
    {
        $this->size = $size;
        $this->claimed = $claimed;
        $this->machineIdentifier = $machineIdentifier;
        $this->version = $version;
    }
}