<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


/**
 * GetSessionsResponseBody - List of Active Plex Sessions
 * 
 * @package LukeHagar\Plex_API\Models\Operations
 * @access public
 */
class GetSessionsResponseBody
{
	#[\JMS\Serializer\Annotation\SerializedName('MediaContainer')]
    #[\JMS\Serializer\Annotation\Type('LukeHagar\Plex_API\Models\Operations\GetSessionsMediaContainer')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?GetSessionsMediaContainer $mediaContainer = null;
    
	public function __construct()
	{
		$this->mediaContainer = null;
	}
}
