<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class GetServerListMediaContainer
{
    /**
     *
     * @var ?float $size
     */
    #[\JMS\Serializer\Annotation\SerializedName('size')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?float $size = null;

    /**
     * $server
     *
     * @var ?array<GetServerListServer> $server
     */
    #[\JMS\Serializer\Annotation\SerializedName('Server')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetServerListServer>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $server = null;

    /**
     * @param  ?float  $size
     * @param  ?array<GetServerListServer>  $server
     */
    public function __construct(?float $size = null, ?array $server = null)
    {
        $this->size = $size;
        $this->server = $server;
    }
}