<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class GetStatisticsDevice
{
    /**
     *
     * @var ?int $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $id = null;

    /**
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     *
     * @var ?string $platform
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('platform')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $platform = null;

    /**
     *
     * @var ?string $clientIdentifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('clientIdentifier')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $clientIdentifier = null;

    /**
     *
     * @var ?int $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $createdAt = null;

    /**
     * @param  ?int  $id
     * @param  ?string  $name
     * @param  ?string  $platform
     * @param  ?string  $clientIdentifier
     * @param  ?int  $createdAt
     * @phpstan-pure
     */
    public function __construct(?int $id = null, ?string $name = null, ?string $platform = null, ?string $clientIdentifier = null, ?int $createdAt = null)
    {
        $this->id = $id;
        $this->name = $name;
        $this->platform = $platform;
        $this->clientIdentifier = $clientIdentifier;
        $this->createdAt = $createdAt;
    }
}