<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


/** String representation of subscriptionActive */
enum GetTokenDetailsAuthenticationStatus: string
{
    case Inactive = 'Inactive';
    case Active = 'Active';
}
