<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


enum GetTokenDetailsFeatures: string
{
    case AndroidDolbyVision = 'Android - Dolby Vision';
    case AndroidPiP = 'Android - PiP';
    case CUSunset = 'CU Sunset';
    case HRKEnableEUR = 'HRK_enable_EUR';
    case TREBLEShowFeatures = 'TREBLE-show-features';
    case AdCountdownTimer = 'ad-countdown-timer';
    case AdaptiveBitrate = 'adaptive_bitrate';
    case AlbumTypes = 'album-types';
    case AllowDvr = 'allow_dvr';
    case AmazonLoopDebug = 'amazon-loop-debug';
    case AvodAdAnalysis = 'avod-ad-analysis';
    case AvodNewMedia = 'avod-new-media';
    case BlacklistGetSignin = 'blacklist_get_signin';
    case BoostVoices = 'boost-voices';
    case CameraUpload = 'camera_upload';
    case ClientRadioStations = 'client-radio-stations';
    case CloudflareTurnstileRequired = 'cloudflare-turnstile-required';
    case Cloudsync = 'cloudsync';
    case Collections = 'collections';
    case CommentsAndRepliesPushNotifications = 'comments_and_replies_push_notifications';
    case CommunityAccessPlexTv = 'community_access_plex_tv';
    case CompanionsSonos = 'companions_sonos';
    case ContentFilter = 'content_filter';
    case CustomHomeRemoval = 'custom-home-removal';
    case DisableHomeUserFriendships = 'disable_home_user_friendships';
    case DisableSharingFriendships = 'disable_sharing_friendships';
    case DownloadsGating = 'downloads-gating';
    case DrmSupport = 'drm_support';
    case Dvr = 'dvr';
    case DvrBlockUnsupportedCountries = 'dvr-block-unsupported-countries';
    case EpgRecentChannels = 'epg-recent-channels';
    case ExcludeRestrictions = 'exclude restrictions';
    case FederatedAuth = 'federated-auth';
    case FriendRequestPushNotifications = 'friend_request_push_notifications';
    case GrandfatherSync = 'grandfather-sync';
    case GuidedUpgrade = 'guided-upgrade';
    case HardwareTranscoding = 'hardware_transcoding';
    case Home = 'home';
    case Hwtranscode = 'hwtranscode';
    case ImaggaV2 = 'imagga-v2';
    case IncreasePasswordComplexity = 'increase-password-complexity';
    case Ios14PrivacyBanner = 'ios14-privacy-banner';
    case IterableNotificationTokens = 'iterable-notification-tokens';
    case ItemClusters = 'item_clusters';
    case KeepPaymentMethod = 'keep-payment-method';
    case KevinBacon = 'kevin-bacon';
    case KoreaConsent = 'korea-consent';
    case LeIsrgRootX1 = 'le_isrg_root_x1';
    case LetsEncrypt = 'lets_encrypt';
    case LightningDvrPivot = 'lightning-dvr-pivot';
    case LiveTvSupportIncompleteSegments = 'live-tv-support-incomplete-segments';
    case Livetv = 'livetv';
    case Lyrics = 'lyrics';
    case MetadataSearch = 'metadata_search';
    case MusicAnalysis = 'music-analysis';
    case MusicVideos = 'music_videos';
    case NewPlexPassPrices = 'new_plex_pass_prices';
    case NewsProviderSunsetModal = 'news-provider-sunset-modal';
    case Nominatim = 'nominatim';
    case Pass = 'pass';
    case PhotosFavorites = 'photos-favorites';
    case PhotosMetadataEdition = 'photos-metadata-edition';
    case PhotosV6Edit = 'photosV6-edit';
    case PhotosV6TvAlbums = 'photosV6-tv-albums';
    case PmsHealth = 'pms_health';
    case PremiumDashboard = 'premium-dashboard';
    case PremiumMusicMetadata = 'premium_music_metadata';
    case Radio = 'radio';
    case RateLimitClientToken = 'rate-limit-client-token';
    case ScrobblingServicePlexTv = 'scrobbling-service-plex-tv';
    case SessionBandwidthRestrictions = 'session_bandwidth_restrictions';
    case SessionKick = 'session_kick';
    case SharedServerNotification = 'shared_server_notification';
    case SharedSourceNotification = 'shared_source_notification';
    case SigninNotification = 'signin_notification';
    case SigninWithApple = 'signin_with_apple';
    case SilenceRemoval = 'silence-removal';
    case SleepTimer = 'sleep-timer';
    case SpringServeAdProvider = 'spring_serve_ad_provider';
    case Sync = 'sync';
    case SweetFades = 'sweet-fades';
    case TranscoderCache = 'transcoder_cache';
    case Trailers = 'trailers';
    case TunerSharing = 'tuner-sharing';
    case TwoFactorAuthentication = 'two-factor-authentication';
    case Unsupportedtuners = 'unsupportedtuners';
    case Upgrade3ds2 = 'upgrade-3ds2';
    case Visualizers = 'visualizers';
    case VodSchema = 'vod-schema';
    case VodCloudflare = 'vod_cloudflare';
    case VolumeLeveling = 'volume-leveling';
    case WatchTogetherInvite = 'watch-together-invite';
    case WatchlistRss = 'watchlist-rss';
    case WebServerDashboard = 'web_server_dashboard';
    case Webhooks = 'webhooks';
}
