<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;

use Brick\DateTime\LocalDate;
class GetTopWatchedContentMetadata
{
    /**
     *
     * @var ?string $ratingKey
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('ratingKey')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $ratingKey = null;

    /**
     *
     * @var ?string $key
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('key')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $key = null;

    /**
     *
     * @var ?string $guid
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('guid')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $guid = null;

    /**
     *
     * @var ?string $slug
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('slug')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $slug = null;

    /**
     *
     * @var ?string $studio
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('studio')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $studio = null;

    /**
     *
     * @var ?string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $type = null;

    /**
     *
     * @var ?string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $title = null;

    /**
     *
     * @var ?string $librarySectionTitle
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('librarySectionTitle')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $librarySectionTitle = null;

    /**
     *
     * @var ?int $librarySectionID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('librarySectionID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $librarySectionID = null;

    /**
     *
     * @var ?string $librarySectionKey
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('librarySectionKey')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $librarySectionKey = null;

    /**
     *
     * @var ?string $contentRating
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('contentRating')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $contentRating = null;

    /**
     *
     * @var ?string $summary
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('summary')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $summary = null;

    /**
     *
     * @var ?int $index
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('index')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $index = null;

    /**
     *
     * @var ?float $audienceRating
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('audienceRating')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $audienceRating = null;

    /**
     *
     * @var ?int $year
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('year')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $year = null;

    /**
     *
     * @var ?string $tagline
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tagline')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $tagline = null;

    /**
     *
     * @var ?string $thumb
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('thumb')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $thumb = null;

    /**
     *
     * @var ?string $art
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('art')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $art = null;

    /**
     *
     * @var ?int $duration
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('duration')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $duration = null;

    /**
     *
     * @var ?LocalDate $originallyAvailableAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('originallyAvailableAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?LocalDate $originallyAvailableAt = null;

    /**
     *
     * @var ?int $leafCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('leafCount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $leafCount = null;

    /**
     *
     * @var ?int $viewedLeafCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('viewedLeafCount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $viewedLeafCount = null;

    /**
     *
     * @var ?int $childCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('childCount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $childCount = null;

    /**
     *
     * @var ?int $addedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('addedAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $addedAt = null;

    /**
     *
     * @var ?int $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updatedAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $updatedAt = null;

    /**
     *
     * @var ?int $globalViewCount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('globalViewCount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $globalViewCount = null;

    /**
     *
     * @var ?string $audienceRatingImage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('audienceRatingImage')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $audienceRatingImage = null;

    /**
     * $genre
     *
     * @var ?array<GetTopWatchedContentGenre> $genre
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('Genre')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetTopWatchedContentGenre>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $genre = null;

    /**
     * $country
     *
     * @var ?array<GetTopWatchedContentCountry> $country
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('Country')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetTopWatchedContentCountry>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $country = null;

    /**
     * $guids
     *
     * @var ?array<GetTopWatchedContentGuids> $guids
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('Guid')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetTopWatchedContentGuids>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $guids = null;

    /**
     * $role
     *
     * @var ?array<GetTopWatchedContentRole> $role
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('Role')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetTopWatchedContentRole>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $role = null;

    /**
     * $user
     *
     * @var ?array<User> $user
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('User')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\User>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $user = null;

    /**
     * @param  ?string  $ratingKey
     * @param  ?string  $key
     * @param  ?string  $guid
     * @param  ?string  $slug
     * @param  ?string  $studio
     * @param  ?string  $type
     * @param  ?string  $title
     * @param  ?string  $librarySectionTitle
     * @param  ?int  $librarySectionID
     * @param  ?string  $librarySectionKey
     * @param  ?string  $contentRating
     * @param  ?string  $summary
     * @param  ?int  $index
     * @param  ?float  $audienceRating
     * @param  ?int  $year
     * @param  ?string  $tagline
     * @param  ?string  $thumb
     * @param  ?string  $art
     * @param  ?int  $duration
     * @param  ?LocalDate  $originallyAvailableAt
     * @param  ?int  $leafCount
     * @param  ?int  $viewedLeafCount
     * @param  ?int  $childCount
     * @param  ?int  $addedAt
     * @param  ?int  $updatedAt
     * @param  ?int  $globalViewCount
     * @param  ?string  $audienceRatingImage
     * @param  ?array<GetTopWatchedContentGenre>  $genre
     * @param  ?array<GetTopWatchedContentCountry>  $country
     * @param  ?array<GetTopWatchedContentGuids>  $guids
     * @param  ?array<GetTopWatchedContentRole>  $role
     * @param  ?array<User>  $user
     */
    public function __construct(?string $ratingKey = null, ?string $key = null, ?string $guid = null, ?string $slug = null, ?string $studio = null, ?string $type = null, ?string $title = null, ?string $librarySectionTitle = null, ?int $librarySectionID = null, ?string $librarySectionKey = null, ?string $contentRating = null, ?string $summary = null, ?int $index = null, ?float $audienceRating = null, ?int $year = null, ?string $tagline = null, ?string $thumb = null, ?string $art = null, ?int $duration = null, ?LocalDate $originallyAvailableAt = null, ?int $leafCount = null, ?int $viewedLeafCount = null, ?int $childCount = null, ?int $addedAt = null, ?int $updatedAt = null, ?int $globalViewCount = null, ?string $audienceRatingImage = null, ?array $genre = null, ?array $country = null, ?array $guids = null, ?array $role = null, ?array $user = null)
    {
        $this->ratingKey = $ratingKey;
        $this->key = $key;
        $this->guid = $guid;
        $this->slug = $slug;
        $this->studio = $studio;
        $this->type = $type;
        $this->title = $title;
        $this->librarySectionTitle = $librarySectionTitle;
        $this->librarySectionID = $librarySectionID;
        $this->librarySectionKey = $librarySectionKey;
        $this->contentRating = $contentRating;
        $this->summary = $summary;
        $this->index = $index;
        $this->audienceRating = $audienceRating;
        $this->year = $year;
        $this->tagline = $tagline;
        $this->thumb = $thumb;
        $this->art = $art;
        $this->duration = $duration;
        $this->originallyAvailableAt = $originallyAvailableAt;
        $this->leafCount = $leafCount;
        $this->viewedLeafCount = $viewedLeafCount;
        $this->childCount = $childCount;
        $this->addedAt = $addedAt;
        $this->updatedAt = $updatedAt;
        $this->globalViewCount = $globalViewCount;
        $this->audienceRatingImage = $audienceRatingImage;
        $this->genre = $genre;
        $this->country = $country;
        $this->guids = $guids;
        $this->role = $role;
        $this->user = $user;
    }
}