<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


/** GetUpdateStatusResponseBody - The Server Updates */
class GetUpdateStatusResponseBody
{
    /**
     *
     * @var ?GetUpdateStatusMediaContainer $mediaContainer
     */
    #[\JMS\Serializer\Annotation\SerializedName('MediaContainer')]
    #[\JMS\Serializer\Annotation\Type('\LukeHagar\Plex_API\Models\Operations\GetUpdateStatusMediaContainer')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?GetUpdateStatusMediaContainer $mediaContainer = null;

    /**
     * @param  ?GetUpdateStatusMediaContainer  $mediaContainer
     */
    public function __construct(?GetUpdateStatusMediaContainer $mediaContainer = null)
    {
        $this->mediaContainer = $mediaContainer;
    }
}