<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


/**
 * include external media in the results
 *
 *
 */
enum IncludeExternalMedia: int
{
    case One = 1;
    case Zero = 0;
}
