<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


/**
 * Whether or not to include details for a section (types, filters, and sorts).
 *
 * Only exists for backwards compatibility, media providers other than the server libraries have it on always.
 *
 */
enum IncludeDetails: int
{
    case Zero = 0;
    case One = 1;
}
