<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


/** Include Https entries in the results */
enum IncludeHttps: int
{
    case Disable = 0;
    case Enable = 1;
}
