<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class Location
{
    /**
     *
     * @var ?int $id
     */
    #[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $id = null;

    /**
     *
     * @var ?string $path
     */
    #[\JMS\Serializer\Annotation\SerializedName('path')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $path = null;

    /**
     * @param  ?int  $id
     * @param  ?string  $path
     */
    public function __construct(?int $id = null, ?string $path = null)
    {
        $this->id = $id;
        $this->path = $path;
    }
}