<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


/**
 * Meta - The Meta object is only included in the response if the `includeMeta` parameter is set to `1`.
 *
 *
 */
class Meta
{
    /**
     * $type
     *
     * @var ?array<GetLibraryItemsType> $type
     */
    #[\JMS\Serializer\Annotation\SerializedName('Type')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetLibraryItemsType>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $type = null;

    /**
     * $fieldType
     *
     * @var ?array<GetLibraryItemsFieldType> $fieldType
     */
    #[\JMS\Serializer\Annotation\SerializedName('FieldType')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\GetLibraryItemsFieldType>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $fieldType = null;

    /**
     * @param  ?array<GetLibraryItemsType>  $type
     * @param  ?array<GetLibraryItemsFieldType>  $fieldType
     */
    public function __construct(?array $type = null, ?array $fieldType = null)
    {
        $this->type = $type;
        $this->fieldType = $fieldType;
    }
}