<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class Part
{
    /**
     *
     * @var int $id
     */
    #[\JMS\Serializer\Annotation\SerializedName('id')]
    public int $id;

    /**
     *
     * @var string $key
     */
    #[\JMS\Serializer\Annotation\SerializedName('key')]
    public string $key;

    /**
     *
     * @var ?int $duration
     */
    #[\JMS\Serializer\Annotation\SerializedName('duration')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?int $duration = null;

    /**
     *
     * @var string $file
     */
    #[\JMS\Serializer\Annotation\SerializedName('file')]
    public string $file;

    /**
     *
     * @var int $size
     */
    #[\JMS\Serializer\Annotation\SerializedName('size')]
    public int $size;

    /**
     * The container format of the media file.
     *
     *
     *
     * @var string $container
     */
    #[\JMS\Serializer\Annotation\SerializedName('container')]
    public string $container;

    /**
     *
     * @var ?string $audioProfile
     */
    #[\JMS\Serializer\Annotation\SerializedName('audioProfile')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $audioProfile = null;

    /**
     *
     * @var ?bool $has64bitOffsets
     */
    #[\JMS\Serializer\Annotation\SerializedName('has64bitOffsets')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?bool $has64bitOffsets = null;

    /**
     *
     * @var ?bool $optimizedForStreaming
     */
    #[\JMS\Serializer\Annotation\SerializedName('optimizedForStreaming')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?bool $optimizedForStreaming = null;

    /**
     *
     * @var ?string $videoProfile
     */
    #[\JMS\Serializer\Annotation\SerializedName('videoProfile')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $videoProfile = null;

    /**
     *
     * @var ?string $indexes
     */
    #[\JMS\Serializer\Annotation\SerializedName('indexes')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $indexes = null;

    /**
     *
     * @var ?HasThumbnail $hasThumbnail
     */
    #[\JMS\Serializer\Annotation\SerializedName('hasThumbnail')]
    #[\JMS\Serializer\Annotation\Type('\LukeHagar\Plex_API\Models\Operations\HasThumbnail|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?HasThumbnail $hasThumbnail = null;

    /**
     * $stream
     *
     * @var ?array<Stream> $stream
     */
    #[\JMS\Serializer\Annotation\SerializedName('Stream')]
    #[\JMS\Serializer\Annotation\Type('array<\LukeHagar\Plex_API\Models\Operations\Stream>|null')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?array $stream = null;

    /**
     * @param  int  $id
     * @param  string  $key
     * @param  string  $file
     * @param  int  $size
     * @param  string  $container
     * @param  ?int  $duration
     * @param  ?string  $audioProfile
     * @param  ?bool  $has64bitOffsets
     * @param  ?bool  $optimizedForStreaming
     * @param  ?string  $videoProfile
     * @param  ?string  $indexes
     * @param  ?HasThumbnail  $hasThumbnail
     * @param  ?array<Stream>  $stream
     */
    public function __construct(int $id, string $key, string $file, int $size, string $container, ?int $duration = null, ?string $audioProfile = null, ?bool $has64bitOffsets = null, ?bool $optimizedForStreaming = null, ?string $videoProfile = null, ?string $indexes = null, ?HasThumbnail $hasThumbnail = null, ?array $stream = null)
    {
        $this->id = $id;
        $this->key = $key;
        $this->file = $file;
        $this->size = $size;
        $this->container = $container;
        $this->duration = $duration;
        $this->audioProfile = $audioProfile;
        $this->has64bitOffsets = $has64bitOffsets;
        $this->optimizedForStreaming = $optimizedForStreaming;
        $this->videoProfile = $videoProfile;
        $this->indexes = $indexes;
        $this->hasThumbnail = $hasThumbnail;
        $this->stream = $stream;
    }
}