<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;

use LukeHagar\Plex_API\Utils\SpeakeasyMetadata;
class PerformSearchRequest
{
    /**
     * The query term
     *
     * @var string $query
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=query')]
    public string $query;

    /**
     * This gives context to the search, and can result in re-ordering of search result hubs
     *
     * @var ?float $sectionId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=sectionId')]
    public ?float $sectionId = null;

    /**
     * The number of items to return per hub
     *
     * @var ?float $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?float $limit = null;

    /**
     * @param  ?string  $query
     * @param  ?float  $sectionId
     * @param  ?float  $limit
     */
    public function __construct(?string $query = null, ?float $sectionId = null, ?float $limit = null)
    {
        $this->query = $query;
        $this->sectionId = $sectionId;
        $this->limit = $limit;
    }
}