<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class Pivot
{
    /**
     *
     * @var ?string $id
     */
    #[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     *
     * @var ?string $key
     */
    #[\JMS\Serializer\Annotation\SerializedName('key')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $key = null;

    /**
     *
     * @var ?string $type
     */
    #[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $type = null;

    /**
     *
     * @var ?string $title
     */
    #[\JMS\Serializer\Annotation\SerializedName('title')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $title = null;

    /**
     *
     * @var ?string $context
     */
    #[\JMS\Serializer\Annotation\SerializedName('context')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $context = null;

    /**
     *
     * @var ?string $symbol
     */
    #[\JMS\Serializer\Annotation\SerializedName('symbol')]
    #[\JMS\Serializer\Annotation\SkipWhenNull]
    public ?string $symbol = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $key
     * @param  ?string  $type
     * @param  ?string  $title
     * @param  ?string  $context
     * @param  ?string  $symbol
     */
    public function __construct(?string $id = null, ?string $key = null, ?string $type = null, ?string $title = null, ?string $context = null, ?string $symbol = null)
    {
        $this->id = $id;
        $this->key = $key;
        $this->type = $type;
        $this->title = $title;
        $this->context = $context;
        $this->symbol = $symbol;
    }
}