<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


/** type of playlists to return (default is all). */
enum QueryParamSmart: int
{
    case Zero = 0;
    case One = 1;
}
