<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class Release
{
    /**
     *
     * @var ?string $key
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('key')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $key = null;

    /**
     *
     * @var ?string $version
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('version')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $version = null;

    /**
     *
     * @var ?string $added
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('added')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $added = null;

    /**
     *
     * @var ?string $fixed
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fixed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $fixed = null;

    /**
     *
     * @var ?string $downloadURL
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('downloadURL')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $downloadURL = null;

    /**
     *
     * @var ?string $state
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $state = null;

    /**
     * @param  ?string  $key
     * @param  ?string  $version
     * @param  ?string  $added
     * @param  ?string  $fixed
     * @param  ?string  $downloadURL
     * @param  ?string  $state
     */
    public function __construct(?string $key = null, ?string $version = null, ?string $added = null, ?string $fixed = null, ?string $downloadURL = null, ?string $state = null)
    {
        $this->key = $key;
        $this->version = $version;
        $this->added = $added;
        $this->fixed = $fixed;
        $this->downloadURL = $downloadURL;
        $this->state = $state;
    }
}