<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


/** Indicates if the user has restricted access. */
enum Restricted: int
{
    case Disable = 0;
    case Enable = 1;
}
