<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class Role
{
    /**
     * The ID of the tag or actor.
     *
     * @var ?int $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $id = null;

    /**
     * The filter used to find the actor or tag.
     *
     * @var ?string $filter
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('filter')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $filter = null;

    /**
     * The thumbnail of the actor
     *
     * @var ?string $thumb
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('thumb')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $thumb = null;

    /**
     * The name of the tag or actor.
     *
     * @var ?string $tag
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tag')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $tag = null;

    /**
     * Unique identifier for the tag.
     *
     * @var ?string $tagKey
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tagKey')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $tagKey = null;

    /**
     * The role of the actor or tag in the media.
     *
     * @var ?string $role
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('role')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $role = null;

    /**
     * @param  ?int  $id
     * @param  ?string  $filter
     * @param  ?string  $thumb
     * @param  ?string  $tag
     * @param  ?string  $tagKey
     * @param  ?string  $role
     */
    public function __construct(?int $id = null, ?string $filter = null, ?string $thumb = null, ?string $tag = null, ?string $tagKey = null, ?string $role = null)
    {
        $this->id = $id;
        $this->filter = $filter;
        $this->thumb = $thumb;
        $this->tag = $tag;
        $this->tagKey = $tagKey;
        $this->role = $role;
    }
}