<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class Services
{
    /**
     *
     * @var string $identifier
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('identifier')]
    public string $identifier;

    /**
     *
     * @var string $endpoint
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('endpoint')]
    public string $endpoint;

    /**
     *
     * @var ?string $token
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('token')]
    public ?string $token;

    /**
     *
     * @var ?string $secret
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('secret')]
    public ?string $secret;

    /**
     *
     * @var GetTokenDetailsStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\LukeHagar\Plex_API\Models\Operations\GetTokenDetailsStatus')]
    public GetTokenDetailsStatus $status;

    /**
     * @param  string  $identifier
     * @param  string  $endpoint
     * @param  GetTokenDetailsStatus  $status
     * @param  ?string  $token
     * @param  ?string  $secret
     */
    public function __construct(string $identifier, string $endpoint, GetTokenDetailsStatus $status, ?string $token = null, ?string $secret = null)
    {
        $this->identifier = $identifier;
        $this->endpoint = $endpoint;
        $this->status = $status;
        $this->token = $token;
        $this->secret = $secret;
    }
}