<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


/**
 * Setting that indicates the episode ordering for the show.
 *
 * Options:
 *   - None = Library default
 *   - tmdbAiring = The Movie Database (Aired)
 *   - aired = TheTVDB (Aired)
 *   - dvd = TheTVDB (DVD)
 *   - absolute = TheTVDB (Absolute)
 *
 */
enum ShowOrdering: string
{
    case None = 'None';
    case TmdbAiring = 'tmdbAiring';
    case TvdbAired = 'aired';
    case TvdbDvd = 'dvd';
    case TvdbAbsolute = 'absolute';
}
