<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace LukeHagar\Plex_API\Models\Operations;


class StatisticsMedia
{
    /**
     *
     * @var ?int $accountID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('accountID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $accountID = null;

    /**
     *
     * @var ?int $deviceID
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deviceID')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $deviceID = null;

    /**
     *
     * @var ?int $timespan
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timespan')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $timespan = null;

    /**
     *
     * @var ?int $at
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('at')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $at = null;

    /**
     *
     * @var ?int $metadataType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadataType')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $metadataType = null;

    /**
     *
     * @var ?int $count
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('count')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $count = null;

    /**
     *
     * @var ?int $duration
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('duration')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?int $duration = null;

    /**
     * @param  ?int  $accountID
     * @param  ?int  $deviceID
     * @param  ?int  $timespan
     * @param  ?int  $at
     * @param  ?int  $metadataType
     * @param  ?int  $count
     * @param  ?int  $duration
     */
    public function __construct(?int $accountID = null, ?int $deviceID = null, ?int $timespan = null, ?int $at = null, ?int $metadataType = null, ?int $count = null, ?int $duration = null)
    {
        $this->accountID = $accountID;
        $this->deviceID = $deviceID;
        $this->timespan = $timespan;
        $this->at = $at;
        $this->metadataType = $metadataType;
        $this->count = $count;
        $this->duration = $duration;
    }
}